-- Moderator management + live-stream moderation.
--
-- Backfills the migration that commits 467417f and 5116c70 changed the schema
-- without writing. Generated by diffing the schema at a8b59e0 (the last commit
-- where schema and migrations agreed) against HEAD.
--
-- Two statements from that raw diff were removed on purpose, because earlier
-- hand-written migrations already applied them to the database while leaving
-- the schema files behind:
--
--   ALTER TYPE "NotificationType" ADD VALUE 'MODERATOR_DEVICE_CHANGE_REQUESTED'  -> 20260816070000
--   ALTER TABLE "audit_logs" ADD COLUMN "violationReason"    -> 20260816080000
--
-- Re-issuing either would abort the deploy ("enum label already exists" /
-- "column already exists"). What remains matches the CI drift report exactly.

-- CreateEnum
CREATE TYPE "LiveStreamModerationMuteType" AS ENUM ('TEMPORARY', 'PERMANENT');

-- CreateEnum
CREATE TYPE "LiveStreamModerationBanType" AS ENUM ('TEMPORARY', 'PERMANENT');

-- CreateEnum
CREATE TYPE "LiveStreamModerationStatus" AS ENUM ('ACTIVE', 'LIFTED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "LiveStreamReportReason" AS ENUM ('ABUSE', 'SPAM', 'HARASSMENT', 'FAKE_PROFILE', 'HATE_SPEECH', 'BULLYING', 'THREATS', 'SEXUAL_CONTENT', 'INAPPROPRIATE_CONTENT', 'LIVE_STREAM_VIOLATION', 'COMMUNITY_GUIDELINE_VIOLATION', 'OTHER');

-- CreateEnum
CREATE TYPE "LiveStreamReportStatus" AS ENUM ('PENDING', 'REVIEWED', 'DISMISSED', 'ACTIONED');

-- CreateEnum
CREATE TYPE "ModerationApprovalRoomType" AS ENUM ('AUDIO_ROOM', 'VIDEO_ROOM', 'LIVE_STREAM');

-- CreateEnum
CREATE TYPE "ModerationApprovalStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "NotificationType" ADD VALUE 'MODERATION_CASE_ESCALATED';

-- AlterTable
ALTER TABLE "audio_rooms" ADD COLUMN     "region" TEXT;

-- AlterTable
ALTER TABLE "room_reports" ADD COLUMN     "moderatorNotes" TEXT;

-- AlterTable
ALTER TABLE "investigation_recordings" ALTER COLUMN "violationReason" DROP NOT NULL;

-- AlterTable
ALTER TABLE "user_roles" ADD COLUMN     "suspendedAt" TIMESTAMP(3),
ADD COLUMN     "suspendedBy" UUID;

-- AlterTable

-- AlterTable
ALTER TABLE "video_room_reports" ADD COLUMN     "moderatorNotes" TEXT;

-- CreateTable
CREATE TABLE "staff_allowed_ips" (
    "id" UUID NOT NULL,
    "userId" UUID NOT NULL,
    "cidr" TEXT NOT NULL,
    "label" TEXT,
    "addedBy" UUID NOT NULL,
    "addedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "removedBy" UUID,
    "removedAt" TIMESTAMP(3),
    "isActive" BOOLEAN NOT NULL DEFAULT true,

    CONSTRAINT "staff_allowed_ips_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "live_stream_mutes" (
    "id" UUID NOT NULL,
    "streamId" UUID NOT NULL,
    "userId" UUID NOT NULL,
    "moderatorId" UUID NOT NULL,
    "type" "LiveStreamModerationMuteType" NOT NULL,
    "reason" TEXT,
    "expiresAt" TIMESTAMP(3),
    "status" "LiveStreamModerationStatus" NOT NULL DEFAULT 'ACTIVE',
    "liftedBy" UUID,
    "liftedAt" TIMESTAMP(3),
    "createdBy" UUID,
    "updatedBy" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "live_stream_mutes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "live_stream_bans" (
    "id" UUID NOT NULL,
    "streamId" UUID NOT NULL,
    "userId" UUID NOT NULL,
    "moderatorId" UUID NOT NULL,
    "type" "LiveStreamModerationBanType" NOT NULL,
    "reason" TEXT,
    "expiresAt" TIMESTAMP(3),
    "status" "LiveStreamModerationStatus" NOT NULL DEFAULT 'ACTIVE',
    "liftedBy" UUID,
    "liftedAt" TIMESTAMP(3),
    "createdBy" UUID,
    "updatedBy" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "live_stream_bans_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "live_stream_reports" (
    "id" UUID NOT NULL,
    "streamId" UUID NOT NULL,
    "reporterId" UUID NOT NULL,
    "targetUserId" UUID NOT NULL,
    "reason" "LiveStreamReportReason" NOT NULL,
    "description" TEXT,
    "status" "LiveStreamReportStatus" NOT NULL DEFAULT 'PENDING',
    "reviewedBy" UUID,
    "reviewedAt" TIMESTAMP(3),
    "resolutionAction" TEXT,
    "moderatorNotes" TEXT,
    "createdBy" UUID,
    "updatedBy" UUID,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "live_stream_reports_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "moderation_action_approvals" (
    "id" UUID NOT NULL,
    "roomType" "ModerationApprovalRoomType" NOT NULL,
    "roomId" UUID,
    "liveStreamId" UUID,
    "reportId" UUID NOT NULL,
    "proposedBy" UUID NOT NULL,
    "targetUserId" UUID NOT NULL,
    "action" TEXT NOT NULL DEFAULT 'BAN',
    "reason" TEXT,
    "status" "ModerationApprovalStatus" NOT NULL DEFAULT 'PENDING',
    "decidedBy" UUID,
    "decidedAt" TIMESTAMP(3),
    "decisionNote" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "moderation_action_approvals_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "staff_allowed_ips_userId_isActive_idx" ON "staff_allowed_ips"("userId", "isActive");

-- CreateIndex
CREATE INDEX "live_stream_mutes_streamId_status_idx" ON "live_stream_mutes"("streamId", "status");

-- CreateIndex
CREATE INDEX "live_stream_mutes_userId_status_idx" ON "live_stream_mutes"("userId", "status");

-- CreateIndex
CREATE INDEX "live_stream_mutes_status_expiresAt_idx" ON "live_stream_mutes"("status", "expiresAt");

-- CreateIndex
CREATE INDEX "live_stream_bans_streamId_status_idx" ON "live_stream_bans"("streamId", "status");

-- CreateIndex
CREATE INDEX "live_stream_bans_userId_status_idx" ON "live_stream_bans"("userId", "status");

-- CreateIndex
CREATE INDEX "live_stream_bans_status_expiresAt_idx" ON "live_stream_bans"("status", "expiresAt");

-- CreateIndex
CREATE INDEX "live_stream_reports_streamId_status_idx" ON "live_stream_reports"("streamId", "status");

-- CreateIndex
CREATE INDEX "live_stream_reports_targetUserId_idx" ON "live_stream_reports"("targetUserId");

-- CreateIndex
CREATE INDEX "live_stream_reports_reporterId_idx" ON "live_stream_reports"("reporterId");

-- CreateIndex
CREATE INDEX "moderation_action_approvals_status_targetUserId_idx" ON "moderation_action_approvals"("status", "targetUserId");

-- CreateIndex
CREATE INDEX "moderation_action_approvals_proposedBy_status_idx" ON "moderation_action_approvals"("proposedBy", "status");

-- CreateIndex
CREATE INDEX "moderation_action_approvals_reportId_idx" ON "moderation_action_approvals"("reportId");

-- CreateIndex
CREATE INDEX "investigation_recordings_moderatorId_targetUserId_status_idx" ON "investigation_recordings"("moderatorId", "targetUserId", "status");

