/**
 * Standardized audit event constants for platform-wide audit logging.
 * Reusable across all domain modules to ensure consistent telemetry and audit history.
 */
export const AUDIT_EVENTS = {
  // User & Account Events
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_BANNED: 'USER_BANNED',
  USER_UNBANNED: 'USER_UNBANNED',
  USER_DELETED: 'USER_DELETED',
  ACCOUNT_ACTIVATED: 'ACCOUNT_ACTIVATED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_REACTIVATED: 'ACCOUNT_REACTIVATED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_UNLOCKED: 'ACCOUNT_UNLOCKED',
  FORCE_LOGOUT: 'FORCE_LOGOUT',

  // Role & Permission Events
  ROLE_CREATED: 'ROLE_CREATED',
  ROLE_UPDATED: 'ROLE_UPDATED',
  ROLE_DELETED: 'ROLE_DELETED',
  ROLE_ASSIGNED: 'ROLE_ASSIGNED',
  ROLE_REMOVED: 'ROLE_REMOVED',
  USER_ROLE_ASSIGNED: 'USER_ROLE_ASSIGNED',
  USER_ROLE_REMOVED: 'USER_ROLE_REMOVED',
  USER_ROLE_UPDATED: 'USER_ROLE_UPDATED',
  USER_PROMOTED: 'USER_PROMOTED',
  USER_DEMOTED: 'USER_DEMOTED',
  PERMISSION_CREATED: 'PERMISSION_CREATED',
  PERMISSION_GRANTED: 'PERMISSION_GRANTED',
  PERMISSION_REVOKED: 'PERMISSION_REVOKED',
  HIERARCHY_EDGE_CREATED: 'HIERARCHY_EDGE_CREATED',
  HIERARCHY_EDGE_REMOVED: 'HIERARCHY_EDGE_REMOVED',
  SCOPE_ASSIGNED: 'SCOPE_ASSIGNED',
  SCOPE_REMOVED: 'SCOPE_REMOVED',

  // Workforce & Personnel Management Events (Phase 2C)
  WORKFORCE_ASSIGNED: 'WORKFORCE_ASSIGNED',
  WORKFORCE_TRANSFERRED: 'WORKFORCE_TRANSFERRED',
  WORKFORCE_REASSIGNED: 'WORKFORCE_REASSIGNED',
  WORKFORCE_ACTIVATED: 'WORKFORCE_ACTIVATED',
  WORKFORCE_DEACTIVATED: 'WORKFORCE_DEACTIVATED',
  WORKFORCE_SUSPENDED: 'WORKFORCE_SUSPENDED',
  WORKFORCE_RESTORED: 'WORKFORCE_RESTORED',
  REPORTING_MANAGER_CHANGED: 'REPORTING_MANAGER_CHANGED',

  // Platform Configuration Events (Phase 2D)
  SETTING_CREATED: 'SETTING_CREATED',
  SETTING_UPDATED: 'SETTING_UPDATED',
  SETTING_RESET: 'SETTING_RESET',
  FEATURE_FLAG_ENABLED: 'FEATURE_FLAG_ENABLED',
  FEATURE_FLAG_DISABLED: 'FEATURE_FLAG_DISABLED',
  MAINTENANCE_MODE_ENABLED: 'MAINTENANCE_MODE_ENABLED',
  MAINTENANCE_MODE_DISABLED: 'MAINTENANCE_MODE_DISABLED',

  // Treasury & Coin Economy Governance Events (Phase 2E)
  TREASURY_UPDATED: 'TREASURY_UPDATED',
  TREASURY_POLICY_CHANGED: 'TREASURY_POLICY_CHANGED',
  COIN_POLICY_UPDATED: 'COIN_POLICY_UPDATED',
  ECONOMY_FROZEN: 'ECONOMY_FROZEN',
  ECONOMY_RESUMED: 'ECONOMY_RESUMED',
  FINANCIAL_LIMIT_UPDATED: 'FINANCIAL_LIMIT_UPDATED',
  RISK_THRESHOLD_UPDATED: 'RISK_THRESHOLD_UPDATED',

  // Enterprise Wallet & Double-Entry Ledger Events (Phase 3)
  WALLET_CREATED: 'WALLET_CREATED',
  BALANCE_UPDATED: 'BALANCE_UPDATED',
  TRANSACTION_CREATED: 'TRANSACTION_CREATED',
  TRANSACTION_REVERSED: 'TRANSACTION_REVERSED',
  RESERVATION_CREATED: 'RESERVATION_CREATED',
  RESERVATION_RELEASED: 'RESERVATION_RELEASED',
  RESERVATION_CONSUMED: 'RESERVATION_CONSUMED',
  WALLET_LOCKED: 'WALLET_LOCKED',
  WALLET_UNLOCKED: 'WALLET_UNLOCKED',

  // Coin Purchase & Payment Infrastructure Events (Phase 4)
  PURCHASE_ORDER_CREATED: 'PURCHASE_ORDER_CREATED',
  PURCHASE_VERIFIED: 'PURCHASE_VERIFIED',
  PURCHASE_COMPLETED: 'PURCHASE_COMPLETED',
  PURCHASE_FAILED: 'PURCHASE_FAILED',
  PURCHASE_REFUNDED: 'PURCHASE_REFUNDED',
  RECEIPT_VERIFIED: 'RECEIPT_VERIFIED',

  // Enterprise Gift Engine Events (Phase 5)
  GIFT_CREATED: 'GIFT_CREATED',
  GIFT_UPDATED: 'GIFT_UPDATED',
  GIFT_SENT: 'GIFT_SENT',
  GIFT_FAILED: 'GIFT_FAILED',
  GIFT_DISABLED: 'GIFT_DISABLED',
  GIFT_ENABLED: 'GIFT_ENABLED',

  // Organization & Geographic Management Events (Super Admin)
  COUNTRY_CREATED: 'COUNTRY_CREATED',
  COUNTRY_UPDATED: 'COUNTRY_UPDATED',
  COUNTRY_STATUS_CHANGED: 'COUNTRY_STATUS_CHANGED',
  STATE_CREATED: 'STATE_CREATED',
  STATE_UPDATED: 'STATE_UPDATED',
  STATE_STATUS_CHANGED: 'STATE_STATUS_CHANGED',
  REGION_CREATED: 'REGION_CREATED',
  REGION_UPDATED: 'REGION_UPDATED',
  REGION_STATUS_CHANGED: 'REGION_STATUS_CHANGED',
  COUNTRY_MANAGER_ASSIGNED: 'COUNTRY_MANAGER_ASSIGNED',
  COUNTRY_MANAGER_TRANSFERRED: 'COUNTRY_MANAGER_TRANSFERRED',
  COUNTRY_MANAGER_REMOVED: 'COUNTRY_MANAGER_REMOVED',

  // Room Events (Audio & Video)
  ROOM_CREATED: 'ROOM_CREATED',
  ROOM_UPDATED: 'ROOM_UPDATED',
  ROOM_CLOSED: 'ROOM_CLOSED',
  ROOM_DELETED: 'ROOM_DELETED',
  ROOM_USER_MUTED: 'ROOM_USER_MUTED',
  ROOM_USER_KICKED: 'ROOM_USER_KICKED',

  // Agency & Coin Seller Portal Events
  AGENCY_CREATED: 'AGENCY_CREATED',
  AGENCY_APPROVED: 'AGENCY_APPROVED',
  AGENCY_REJECTED: 'AGENCY_REJECTED',
  SELLER_APPROVED: 'SELLER_APPROVED',
  SELLER_REJECTED: 'SELLER_REJECTED',

  // Wallet & Economy Events
  WALLET_ADJUSTED: 'WALLET_ADJUSTED',
  WALLET_FROZEN: 'WALLET_FROZEN',
  GIFT_CONFIG_CHANGED: 'GIFT_CONFIG_CHANGED',
  COIN_CONFIG_CHANGED: 'COIN_CONFIG_CHANGED',

  // Events & Analytics
  EVENT_CREATED: 'EVENT_CREATED',
  EVENT_PUBLISHED: 'EVENT_PUBLISHED',
  EVENT_CANCELLED: 'EVENT_CANCELLED',
} as const;

export type AuditEventType = (typeof AUDIT_EVENTS)[keyof typeof AUDIT_EVENTS];
