// Platform Default System Roles
export const SYSTEM_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  COUNTRY_MANAGER: 'COUNTRY_MANAGER',
  OFFICIAL: 'OFFICIAL',
  MODERATOR: 'MODERATOR',
  BUSINESS_DEVELOPMENT: 'BUSINESS_DEVELOPMENT',
  AGENCY: 'AGENCY',
  COIN_SELLER: 'COIN_SELLER',
  HOST: 'HOST',
  USER: 'USER',
} as const;

export type SystemRoleType = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

// Permission Categories
export const PERMISSION_CATEGORIES = [
  'USER',
  'ROOM',
  'AUDIO_ROOM',
  'VIDEO_ROOM',
  'WALLET',
  'GIFTS',
  'COIN',
  'VIP',
  'FAMILY',
  'GAME',
  'EVENT',
  'ANALYTICS',
  'AGENCY',
  'COIN_SELLER',
  'TREASURE',
  'REVENUE',
  'WITHDRAWAL',
  'ACHIEVEMENT',
  'LEVEL',
  'RANKING',
  'TASK',
  'POST',
  'REFERRAL',
  'NOTIFICATION',
  'DASHBOARD',
  'SYSTEM',
] as const;

export type PermissionCategory = (typeof PERMISSION_CATEGORIES)[number];

// Standard Granular Permissions across all Soulzaa Platform Modules
export const DEFAULT_PERMISSIONS = [
  // Enterprise Gift Engine (Phase 5)
  {
    code: 'gift.catalog.view',
    module: 'gifts',
    action: 'view',
    category: 'ROOM',
    displayName: 'View Gift Catalog',
    description: 'Can view and manage gift catalog and categories',
  },
  {
    code: 'gift.send',
    module: 'gifts',
    action: 'send',
    category: 'ROOM',
    displayName: 'Send Gift',
    description: 'Can send gifts in audio/video rooms, PK battles, and chats',
  },
  {
    code: 'gift.history.view',
    module: 'gifts',
    action: 'view',
    category: 'ROOM',
    displayName: 'View Gift History',
    description: 'Can view gift transaction history and logs',
  },
  {
    code: 'gift.transaction.view',
    module: 'gifts',
    action: 'view',
    category: 'GIFTS',
    displayName: 'View Gift Transactions',
    description: 'Can view the platform-wide gift transaction log across all users',
  },
  {
    code: 'gift.audit.view',
    module: 'gifts',
    action: 'view',
    category: 'ROOM',
    displayName: 'View Gift Audit',
    description: 'Can view gift operational audit trail',
  },

  // Coin Purchase & Payment Infrastructure (Phase 4)
  {
    code: 'purchase.package.view',
    module: 'payments',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Coin Packages',
    description: 'Can view and manage purchasable coin packages catalog',
  },
  {
    code: 'purchase.order.view',
    module: 'payments',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Purchase Orders',
    description: 'Can view purchase order history and verification status',
  },
  {
    code: 'purchase.audit.view',
    module: 'payments',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Purchase Audit',
    description: 'Can view purchase verification and order audit trail',
  },
  {
    code: 'purchase.verify',
    module: 'payments',
    action: 'verify',
    category: 'WALLET',
    displayName: 'Verify Purchases',
    description: 'Can verify IAP receipts and trigger manual re-verifications',
  },

  // Enterprise Wallet & Double-Entry Ledger (Phase 3)
  {
    code: 'wallet.view',
    module: 'wallet',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Wallet Accounts',
    description: 'Can view platform wallet accounts and metrics',
  },
  {
    code: 'wallet.balance.view',
    module: 'wallet',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Wallet Balances',
    description: 'Can view detailed wallet balance projections and reconciliations',
  },
  {
    code: 'wallet.transaction.view',
    module: 'wallet',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Wallet Transactions',
    description: 'Can view wallet transactions and immutable ledger entries',
  },
  {
    code: 'wallet.reservation.view',
    module: 'wallet',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Wallet Reservations',
    description: 'Can view active and historical coin reservation holds',
  },
  {
    code: 'wallet.audit.view',
    module: 'wallet',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Wallet Audit',
    description: 'Can view wallet audit history logs',
  },

  // Super Admin Treasury & Coin Economy Governance (Phase 2E)
  {
    code: 'treasury.summary.view',
    module: 'treasury',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Treasury Summary',
    description: 'Can view treasury reserve balances and coin supply stats',
  },
  {
    code: 'treasury.economy.view',
    module: 'treasury',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Economy Breakdown',
    description: 'Can view coin circulating, reserved, and max supply metrics',
  },
  {
    code: 'treasury.health.view',
    module: 'treasury',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Financial Health',
    description: 'Can view reserve ratio and financial health indicators',
  },
  {
    code: 'treasury.policies.view',
    module: 'treasury',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Financial Policies',
    description: 'Can view financial limit policies and threshold bounds',
  },
  {
    code: 'treasury.policies.update',
    module: 'treasury',
    action: 'update',
    category: 'WALLET',
    displayName: 'Update Financial Policies',
    description: 'Can modify financial limit policies and threshold bounds',
  },
  {
    code: 'treasury.risk.view',
    module: 'treasury',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Risk Controls',
    description: 'Can view financial emergency freeze and risk control flags',
  },
  {
    code: 'treasury.risk.manage',
    module: 'treasury',
    action: 'manage',
    category: 'WALLET',
    displayName: 'Manage Risk Controls',
    description: 'Can execute emergency freeze or resume on financial features',
  },
  {
    code: 'treasury.audit.view',
    module: 'treasury',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Treasury Audit',
    description: 'Can view treasury operational audit trail',
  },

  // Super Admin Platform Configuration & Global Settings (Phase 2D)
  {
    code: 'config.settings.view',
    module: 'config',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Settings',
    description: 'Can view global platform settings and categories',
  },
  {
    code: 'config.settings.update',
    module: 'config',
    action: 'update',
    category: 'SYSTEM',
    displayName: 'Update Setting',
    description: 'Can modify global platform settings',
  },
  {
    code: 'config.settings.reset',
    module: 'config',
    action: 'reset',
    category: 'SYSTEM',
    displayName: 'Reset Setting',
    description: 'Can reset platform setting to default value',
  },
  {
    code: 'config.flags.view',
    module: 'config',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Feature Flags',
    description: 'Can view platform feature flag statuses',
  },
  {
    code: 'config.flags.manage',
    module: 'config',
    action: 'manage',
    category: 'SYSTEM',
    displayName: 'Manage Feature Flags',
    description: 'Can enable, disable, or toggle feature flags',
  },
  {
    code: 'config.history.view',
    module: 'config',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Config History',
    description: 'Can view platform configuration change audit history',
  },

  // Admin identity — provisioning hidden Moderator accounts. Admin and above only:
  // this grants the power to create anonymous accounts that can act as Moderators.
  {
    code: 'admin.identity.manage',
    module: 'admin',
    action: 'manage',
    category: 'SYSTEM',
    displayName: 'Manage Moderator Accounts',
    description:
      'Can create, list, suspend and restore hidden Moderator accounts; also manages staff IP allowlists',
  },

  // Super Admin only: can mint Admins (platform-wide authority).
  {
    code: 'admin.provision',
    module: 'admin',
    action: 'manage',
    category: 'SYSTEM',
    displayName: 'Provision Admin Accounts',
    description: 'Can create, list, suspend and restore hidden Admin accounts',
  },

  // Super Admin Workforce & Operational Personnel Management (Phase 2C)
  {
    code: 'workforce.list.view',
    module: 'workforce',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Workforce List',
    description: 'Can view and search operational workforce personnel',
  },
  {
    code: 'workforce.detail.view',
    module: 'workforce',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Workforce Details',
    description: 'Can view operational status, workload summary, and assignment history',
  },
  {
    code: 'workforce.assign',
    module: 'workforce',
    action: 'assign',
    category: 'SYSTEM',
    displayName: 'Assign Workforce',
    description: 'Can assign operational scope to personnel',
  },
  {
    code: 'workforce.transfer',
    module: 'workforce',
    action: 'transfer',
    category: 'SYSTEM',
    displayName: 'Transfer Workforce',
    description: 'Can transfer or reassign operational personnel scope',
  },
  {
    code: 'workforce.status.manage',
    module: 'workforce',
    action: 'manage',
    category: 'SYSTEM',
    displayName: 'Manage Workforce Status',
    description: 'Can activate, deactivate, suspend, or restore personnel operational status',
  },
  {
    code: 'workforce.hierarchy.view',
    module: 'workforce',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Reporting Hierarchy',
    description: 'Can view full operational reporting hierarchy graph',
  },

  // Super Admin Organization & Geographic Management
  {
    code: 'organization.country.manage',
    module: 'organization',
    action: 'manage',
    category: 'SYSTEM',
    displayName: 'Manage Countries',
    description: 'Can create, update, activate and deactivate countries',
  },
  {
    code: 'organization.state.manage',
    module: 'organization',
    action: 'manage',
    category: 'SYSTEM',
    displayName: 'Manage States',
    description: 'Can create, update, activate and deactivate states',
  },
  {
    code: 'organization.region.manage',
    module: 'organization',
    action: 'manage',
    category: 'SYSTEM',
    displayName: 'Manage Regions',
    description: 'Can create, update, activate and deactivate regions',
  },
  {
    code: 'organization.manager.assign',
    module: 'organization',
    action: 'assign',
    category: 'SYSTEM',
    displayName: 'Assign Country Managers',
    description: 'Can assign, transfer, or remove Country Managers',
  },
  {
    code: 'organization.hierarchy.view',
    module: 'organization',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Organization Hierarchy',
    description: 'Can view complete organizational hierarchy graph',
  },

  // User Management
  {
    code: 'user.view',
    module: 'user',
    action: 'view',
    category: 'USER',
    displayName: 'View Users',
    description: 'Can view user profile details and list users',
  },
  {
    code: 'user.update',
    module: 'user',
    action: 'update',
    category: 'USER',
    displayName: 'Update User',
    description: 'Can update user profiles and account details',
  },
  {
    code: 'user.ban',
    module: 'user',
    action: 'ban',
    category: 'USER',
    displayName: 'Ban User',
    description: 'Can suspend or ban user accounts',
  },
  {
    code: 'user.delete',
    module: 'user',
    action: 'delete',
    category: 'USER',
    displayName: 'Delete User',
    description: 'Can soft or hard delete user accounts',
  },

  // Wallet & Financial — `wallet.view` is declared once with the Phase 3 ledger block above.
  {
    code: 'wallet.adjust',
    module: 'wallet',
    action: 'adjust',
    category: 'WALLET',
    displayName: 'Adjust Wallet',
    description: 'Can credit/debit user balances manually',
  },

  // Audio & Video Rooms
  {
    code: 'room.create',
    module: 'room',
    action: 'create',
    category: 'ROOM',
    displayName: 'Create Room',
    description: 'Can create audio/video rooms',
  },
  {
    code: 'room.update',
    module: 'room',
    action: 'update',
    category: 'ROOM',
    displayName: 'Update Room',
    description: 'Can update room settings and metadata',
  },
  {
    code: 'room.close',
    module: 'room',
    action: 'close',
    category: 'ROOM',
    displayName: 'Close Room',
    description: 'Can forcefully close audio/video rooms',
  },
  {
    code: 'room.delete',
    module: 'room',
    action: 'delete',
    category: 'ROOM',
    displayName: 'Delete Room',
    description: 'Can delete room records',
  },
  {
    code: 'room.mute',
    module: 'room',
    action: 'mute',
    category: 'ROOM',
    displayName: 'Mute Room User',
    description: 'Can mute users in audio/video rooms',
  },

  // Agency Portal & Management
  {
    code: 'agency.create',
    module: 'agency',
    action: 'create',
    category: 'AGENCY',
    displayName: 'Create Agency',
    description: 'Can create new host/talent agencies',
  },
  {
    code: 'agency.approve',
    module: 'agency',
    action: 'approve',
    category: 'AGENCY',
    displayName: 'Approve Agency',
    description: 'Can approve agency registration requests',
  },
  {
    code: 'agency.reject',
    module: 'agency',
    action: 'reject',
    category: 'AGENCY',
    displayName: 'Reject Agency',
    description: 'Can reject agency registration requests',
  },

  // Coin Seller
  {
    code: 'seller.approve',
    module: 'seller',
    action: 'approve',
    category: 'COIN_SELLER',
    displayName: 'Approve Coin Seller',
    description: 'Can approve coin seller applications',
  },
  {
    code: 'seller.reject',
    module: 'seller',
    action: 'reject',
    category: 'COIN_SELLER',
    displayName: 'Reject Coin Seller',
    description: 'Can reject coin seller applications',
  },

  // Events
  {
    code: 'event.create',
    module: 'event',
    action: 'create',
    category: 'EVENT',
    displayName: 'Create Event',
    description: 'Can create platform events',
  },
  {
    code: 'event.publish',
    module: 'event',
    action: 'publish',
    category: 'EVENT',
    displayName: 'Publish Event',
    description: 'Can publish scheduled events',
  },
  {
    code: 'event.submit_for_approval',
    module: 'event',
    action: 'submit_for_approval',
    category: 'EVENT',
    displayName: 'Submit Event For Approval',
    description: 'Can submit a draft event for Official/Admin approval',
  },

  // Analytics
  {
    code: 'analytics.view',
    module: 'analytics',
    action: 'view',
    category: 'ANALYTICS',
    displayName: 'View Analytics',
    description: 'Can view platform analytics and operational metrics',
  },

  // Module Management
  {
    code: 'gift.manage',
    module: 'gift',
    action: 'manage',
    category: 'GIFTS',
    displayName: 'Manage Gifts',
    description: 'Can configure virtual gifts and pricing',
  },
  {
    code: 'coin.manage',
    module: 'coin',
    action: 'manage',
    category: 'COIN',
    displayName: 'Manage Coins',
    description: 'Can manage coin rates, packages, and distributions',
  },
  {
    code: 'game.manage',
    module: 'game',
    action: 'manage',
    category: 'GAME',
    displayName: 'Manage Games',
    description: 'Can configure platform mini-games and rules',
  },
  // Authorization administration (RBAC self-management)
  {
    code: 'role.manage',
    module: 'authorization',
    action: 'manage',
    category: 'SYSTEM',
    displayName: 'Manage Roles',
    description: 'Can create, update, and deactivate platform roles',
  },
  {
    code: 'role.assign',
    module: 'authorization',
    action: 'assign',
    category: 'SYSTEM',
    displayName: 'Assign Roles',
    description: 'Can assign and revoke roles for a user',
  },
  {
    code: 'role.hierarchy.manage',
    module: 'authorization',
    action: 'manage',
    category: 'SYSTEM',
    displayName: 'Manage Role Hierarchy',
    description: 'Can define parent/child inheritance edges between roles',
  },
  {
    code: 'permission.manage',
    module: 'authorization',
    action: 'manage',
    category: 'SYSTEM',
    displayName: 'Manage Permissions',
    description: 'Can create permissions and map them to roles',
  },
  {
    code: 'scope.manage',
    module: 'authorization',
    action: 'manage',
    category: 'SYSTEM',
    displayName: 'Manage Geographic Scope',
    description: 'Can assign country/state/region scope to a role assignment',
  },
  {
    code: 'audit.view',
    module: 'authorization',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Audit Logs',
    description: 'Can read the immutable platform audit trail',
  },

  // Super Admin user & account lifecycle (Phase 2B)
  {
    code: 'user.list.view',
    module: 'users',
    action: 'view',
    category: 'USER',
    displayName: 'List Users',
    description: 'Can search, filter, and page through platform users',
  },
  {
    code: 'user.profile.view',
    module: 'users',
    action: 'view',
    category: 'USER',
    displayName: 'View User Profile',
    description: 'Can open a full user profile with roles, scopes, and status',
  },
  {
    code: 'user.audit.view',
    module: 'users',
    action: 'view',
    category: 'USER',
    displayName: 'View User Audit History',
    description: 'Can read a user audit and role-assignment history',
  },
  {
    code: 'user.role.assign',
    module: 'users',
    action: 'assign',
    category: 'USER',
    displayName: 'Assign User Role',
    description: 'Can grant a role to a user',
  },
  {
    code: 'user.role.remove',
    module: 'users',
    action: 'remove',
    category: 'USER',
    displayName: 'Remove User Role',
    description: 'Can revoke a role from a user',
  },
  {
    code: 'user.role.update',
    module: 'users',
    action: 'update',
    category: 'USER',
    displayName: 'Update User Role',
    description: 'Can change (promote/demote) a role assignment',
  },
  {
    code: 'user.status.activate',
    module: 'users',
    action: 'update',
    category: 'USER',
    displayName: 'Activate Account',
    description: 'Can activate or restore a user account',
  },
  {
    code: 'user.status.suspend',
    module: 'users',
    action: 'update',
    category: 'USER',
    displayName: 'Suspend Account',
    description: 'Can suspend a user account',
  },
  {
    code: 'user.status.lock',
    module: 'users',
    action: 'update',
    category: 'USER',
    displayName: 'Lock Account',
    description: 'Can lock a user account',
  },
  {
    code: 'user.status.unlock',
    module: 'users',
    action: 'update',
    category: 'USER',
    displayName: 'Unlock Account',
    description: 'Can unlock a locked user account',
  },
  {
    code: 'user.session.force_logout',
    module: 'users',
    action: 'update',
    category: 'USER',
    displayName: 'Force Logout',
    description: 'Can invalidate all active sessions for a user',
  },

  // Treasure Box Engine (Phase 6)
  {
    code: 'treasure.configuration.manage',
    module: 'treasure',
    action: 'manage',
    category: 'TREASURE',
    displayName: 'Manage Treasure Configuration',
    description: 'Can configure treasure box thresholds, rewards, and reset policy',
  },

  // Host Earnings & Revenue Distribution (Phase 7)
  {
    code: 'revenue.view',
    module: 'revenue',
    action: 'view',
    category: 'REVENUE',
    displayName: 'View Revenue',
    description: 'Can view revenue summaries and host earnings',
  },
  {
    code: 'revenue.history.view',
    module: 'revenue',
    action: 'view',
    category: 'REVENUE',
    displayName: 'View Revenue History',
    description: 'Can view historical revenue distributions',
  },
  {
    code: 'revenue.audit.view',
    module: 'revenue',
    action: 'view',
    category: 'REVENUE',
    displayName: 'View Revenue Audit',
    description: 'Can read the revenue distribution audit trail',
  },
  {
    code: 'revenue.configuration.manage',
    module: 'revenue',
    action: 'manage',
    category: 'REVENUE',
    displayName: 'Manage Revenue Configuration',
    description: 'Can configure host/platform revenue split percentages',
  },

  // Agency Settlement Engine (Phase 8)
  {
    code: 'agency.settlement.view',
    module: 'agencies',
    action: 'view',
    category: 'AGENCY',
    displayName: 'View Agency Settlements',
    description: 'Can view agency settlement summaries and earnings',
  },
  {
    code: 'agency.settlement.history.view',
    module: 'agencies',
    action: 'view',
    category: 'AGENCY',
    displayName: 'View Agency Settlement History',
    description: 'Can view historical agency settlements',
  },
  {
    code: 'agency.settlement.audit.view',
    module: 'agencies',
    action: 'view',
    category: 'AGENCY',
    displayName: 'View Agency Settlement Audit',
    description: 'Can read the agency settlement audit trail',
  },
  {
    code: 'agency.settlement.configuration.manage',
    module: 'agencies',
    action: 'manage',
    category: 'AGENCY',
    displayName: 'Manage Agency Commission Configuration',
    description: 'Can configure agency commission percentages and rounding',
  },

  // Coin Seller Settlement Engine (Phase 9)
  {
    code: 'coin_seller.settlement.view',
    module: 'coin_seller',
    action: 'view',
    category: 'COIN_SELLER',
    displayName: 'View Seller Settlements',
    description: 'Can view coin seller settlement summaries and earnings',
  },
  {
    code: 'coin_seller.settlement.history.view',
    module: 'coin_seller',
    action: 'view',
    category: 'COIN_SELLER',
    displayName: 'View Seller Settlement History',
    description: 'Can view historical coin seller settlements',
  },
  {
    code: 'coin_seller.settlement.audit.view',
    module: 'coin_seller',
    action: 'view',
    category: 'COIN_SELLER',
    displayName: 'View Seller Settlement Audit',
    description: 'Can read the coin seller settlement audit trail',
  },
  {
    code: 'coin_seller.settlement.configuration.manage',
    module: 'coin_seller',
    action: 'manage',
    category: 'COIN_SELLER',
    displayName: 'Manage Seller Commission Configuration',
    description: 'Can configure coin seller commission percentages and limits',
  },
  {
    code: 'coin_seller.inventory.purchase',
    module: 'coin_seller',
    action: 'manage',
    category: 'COIN_SELLER',
    displayName: 'Purchase Inventory',
    description: 'Can purchase coin inventory from the platform',
  },
  {
    code: 'coin_seller.inventory.sell',
    module: 'coin_seller',
    action: 'manage',
    category: 'COIN_SELLER',
    displayName: 'Sell Inventory',
    description: 'Can sell coin inventory to users',
  },
  {
    code: 'coin_seller.inventory.approve',
    module: 'coin_seller',
    action: 'manage',
    category: 'COIN_SELLER',
    displayName: 'Approve Inventory Purchase',
    description: 'Can approve coin seller inventory purchase orders',
  },

  // Withdrawal Engine (Phase 10)
  {
    code: 'withdrawal.request',
    module: 'withdrawals',
    action: 'create',
    category: 'WITHDRAWAL',
    displayName: 'Request Withdrawal',
    description: 'Can submit a withdrawal request against eligible earnings',
  },
  {
    code: 'withdrawal.view',
    module: 'withdrawals',
    action: 'view',
    category: 'WITHDRAWAL',
    displayName: 'View Withdrawals',
    description: 'Can view withdrawal requests and their status',
  },
  {
    code: 'withdrawal.history.view',
    module: 'withdrawals',
    action: 'view',
    category: 'WITHDRAWAL',
    displayName: 'View Withdrawal History',
    description: 'Can view historical withdrawal requests',
  },
  {
    code: 'withdrawal.approve',
    module: 'withdrawals',
    action: 'approve',
    category: 'WITHDRAWAL',
    displayName: 'Approve Withdrawals',
    description: 'Can approve, reject, and execute withdrawal payouts',
  },
  {
    code: 'withdrawal.audit.view',
    module: 'withdrawals',
    action: 'view',
    category: 'WITHDRAWAL',
    displayName: 'View Withdrawal Audit',
    description: 'Can read the withdrawal audit trail',
  },
  {
    code: 'withdrawal.configuration.manage',
    module: 'withdrawals',
    action: 'manage',
    category: 'WITHDRAWAL',
    displayName: 'Manage Withdrawal Configuration',
    description: 'Can configure withdrawal limits, fees, and tax rules',
  },

  // Family System (Phase 11)
  {
    code: 'family.view',
    module: 'families',
    action: 'view',
    category: 'FAMILY',
    displayName: 'View Family',
    description: 'Can view families, members, and history',
  },
  {
    code: 'family.create',
    module: 'families',
    action: 'create',
    category: 'FAMILY',
    displayName: 'Create Family',
    description: 'Can create a family',
  },
  {
    code: 'family.update',
    module: 'families',
    action: 'update',
    category: 'FAMILY',
    displayName: 'Update Family',
    description: 'Can update family profile, announcement, and settings',
  },
  {
    code: 'family.delete',
    module: 'families',
    action: 'delete',
    category: 'FAMILY',
    displayName: 'Delete Family',
    description: 'Can archive or delete a family',
  },
  {
    code: 'family.member.manage',
    module: 'families',
    action: 'manage',
    category: 'FAMILY',
    displayName: 'Manage Family Members',
    description: 'Can invite, approve, kick, ban, and unban family members',
  },
  {
    code: 'family.role.manage',
    module: 'families',
    action: 'manage',
    category: 'FAMILY',
    displayName: 'Manage Family Roles',
    description: 'Can change family roles and transfer ownership',
  },
  {
    code: 'family.audit.view',
    module: 'families',
    action: 'view',
    category: 'FAMILY',
    displayName: 'View Family Audit',
    description: 'Can read the family audit trail',
  },
  {
    code: 'family.statistics.view',
    module: 'families',
    action: 'view',
    category: 'FAMILY',
    displayName: 'View Family Statistics',
    description: 'Can view family activity and contribution statistics',
  },


  // Wealth Level system — the sole VIP progression system (replaces the VIP
  // Membership Engine above; see prisma/schema/wealth.prisma).
  {
    code: 'wealth.view',
    module: 'wealth',
    action: 'view',
    category: 'WEALTH',
    displayName: 'View Wealth Level',
    description: 'Can view Wealth Level, EXP progress, benefits, and rewards',
  },
  {
    code: 'wealth.manage',
    module: 'wealth',
    action: 'manage',
    category: 'WEALTH',
    displayName: 'Manage Wealth Level',
    description: 'Can manage Wealth Level tiers, benefits, and rewards',
  },
  {
    code: 'wealth.configuration.manage',
    module: 'wealth',
    action: 'manage',
    category: 'WEALTH',
    displayName: 'Manage Wealth Level Configuration',
    description: 'Can configure general Wealth Level module parameters',
  },
  {
    code: 'wealth.level.downgrade.manage',
    module: 'wealth',
    action: 'manage',
    category: 'WEALTH',
    displayName: 'Manage Wealth Level Downgrade Policy',
    description: 'Can configure the monthly downgrade policy (max levels, floor, effective dates). SUPER_ADMIN only.',
  },
  {
    code: 'wealth.audit.view',
    module: 'wealth',
    action: 'view',
    category: 'WEALTH',
    displayName: 'View Wealth Level Audit',
    description: 'Can read the Wealth Level configuration audit trail',
  },
  {
    code: 'wealth.statistics.view',
    module: 'wealth',
    action: 'view',
    category: 'WEALTH',
    displayName: 'View Wealth Level Statistics',
    description: 'Can view Wealth Level progression and reward statistics',
  },

  // Level & Experience Engine (Phase 13)
  {
    code: 'level.view',
    module: 'exp',
    action: 'view',
    category: 'LEVEL',
    displayName: 'View Level',
    description: 'Can view user level and progression',
  },
  {
    code: 'level.manage',
    module: 'exp',
    action: 'manage',
    category: 'LEVEL',
    displayName: 'Manage Level',
    description: 'Can award or remove EXP and recalculate levels',
  },
  {
    code: 'level.configuration.manage',
    module: 'exp',
    action: 'manage',
    category: 'LEVEL',
    displayName: 'Manage Level Configuration',
    description: 'Can configure level thresholds, caps, and EXP source values',
  },
  {
    code: 'level.audit.view',
    module: 'exp',
    action: 'view',
    category: 'LEVEL',
    displayName: 'View Level Audit',
    description: 'Can read the level and EXP audit trail',
  },
  {
    code: 'level.statistics.view',
    module: 'exp',
    action: 'view',
    category: 'LEVEL',
    displayName: 'View Level Statistics',
    description: 'Can view EXP and level distribution statistics',
  },

  // Badge & Achievement Engine (Phase 14)
  {
    code: 'achievement.view',
    module: 'achievements',
    action: 'view',
    category: 'ACHIEVEMENT',
    displayName: 'View Achievements',
    description: 'Can view achievements, progress, and badges',
  },
  {
    code: 'achievement.manage',
    module: 'achievements',
    action: 'manage',
    category: 'ACHIEVEMENT',
    displayName: 'Manage Achievements',
    description: 'Can create and update achievement definitions',
  },
  {
    code: 'badge.manage',
    module: 'achievements',
    action: 'manage',
    category: 'ACHIEVEMENT',
    displayName: 'Manage Badges',
    description: 'Can create badges and assign them to roles or events',
  },
  {
    code: 'achievement.configuration.manage',
    module: 'achievements',
    action: 'manage',
    category: 'ACHIEVEMENT',
    displayName: 'Manage Achievement Configuration',
    description: 'Can configure achievement auto-claim and visibility rules',
  },
  {
    code: 'achievement.audit.view',
    module: 'achievements',
    action: 'view',
    category: 'ACHIEVEMENT',
    displayName: 'View Achievement Audit',
    description: 'Can read the achievement audit trail',
  },
  {
    code: 'achievement.statistics.view',
    module: 'achievements',
    action: 'view',
    category: 'ACHIEVEMENT',
    displayName: 'View Achievement Statistics',
    description: 'Can view unlock rates and badge rarity statistics',
  },

  // Ranking Engine (Phase 15)
  {
    code: 'ranking.view',
    module: 'rankings',
    action: 'view',
    category: 'RANKING',
    displayName: 'View Rankings',
    description: 'Can view leaderboards and ranking entries',
  },
  {
    code: 'ranking.manage',
    module: 'rankings',
    action: 'manage',
    category: 'RANKING',
    displayName: 'Manage Rankings',
    description: 'Can recalculate, reset, and snapshot rankings',
  },
  {
    code: 'ranking.configuration.manage',
    module: 'rankings',
    action: 'manage',
    category: 'RANKING',
    displayName: 'Manage Ranking Configuration',
    description: 'Can configure ranking refresh intervals, decay, and visibility',
  },
  {
    code: 'ranking.audit.view',
    module: 'rankings',
    action: 'view',
    category: 'RANKING',
    displayName: 'View Ranking Audit',
    description: 'Can read the ranking audit trail',
  },
  {
    code: 'ranking.statistics.view',
    module: 'rankings',
    action: 'view',
    category: 'RANKING',
    displayName: 'View Ranking Statistics',
    description: 'Can view ranking trends and position-change statistics',
  },

  // Events Engine (Phase 16)
  {
    code: 'event.view',
    module: 'events',
    action: 'view',
    category: 'EVENT',
    displayName: 'View Events',
    description: 'Can view events, schedules, and participants',
  },
  {
    code: 'event.manage',
    module: 'events',
    action: 'manage',
    category: 'EVENT',
    displayName: 'Manage Events',
    description: 'Can create, update, cancel, and archive events',
  },
  {
    code: 'event.configuration.manage',
    module: 'events',
    action: 'manage',
    category: 'EVENT',
    displayName: 'Manage Event Configuration',
    description: 'Can configure participant limits, windows, and claim rules',
  },
  {
    code: 'event.audit.view',
    module: 'events',
    action: 'view',
    category: 'EVENT',
    displayName: 'View Event Audit',
    description: 'Can read the event audit trail',
  },
  {
    code: 'event.statistics.view',
    module: 'events',
    action: 'view',
    category: 'EVENT',
    displayName: 'View Event Statistics',
    description: 'Can view participation and completion statistics',
  },

  // Tasks & Missions Engine (Phase 17)
  {
    code: 'task.view',
    module: 'tasks',
    action: 'view',
    category: 'TASK',
    displayName: 'View Tasks',
    description: 'Can view tasks, missions, and progress',
  },
  {
    code: 'task.manage',
    module: 'tasks',
    action: 'manage',
    category: 'TASK',
    displayName: 'Manage Tasks',
    description: 'Can create and update task and mission definitions',
  },
  {
    code: 'task.configuration.manage',
    module: 'tasks',
    action: 'manage',
    category: 'TASK',
    displayName: 'Manage Task Configuration',
    description: 'Can configure reset policy, claim windows, and auto-claim',
  },
  {
    code: 'task.audit.view',
    module: 'tasks',
    action: 'view',
    category: 'TASK',
    displayName: 'View Task Audit',
    description: 'Can read the task audit trail',
  },
  {
    code: 'task.statistics.view',
    module: 'tasks',
    action: 'view',
    category: 'TASK',
    displayName: 'View Task Statistics',
    description: 'Can view completion rates and reward dispatch counts',
  },

  // Referral System (Phase 18)
  {
    code: 'referral.view',
    module: 'referrals',
    action: 'view',
    category: 'REFERRAL',
    displayName: 'View Referrals',
    description: 'Can view referral codes, relationships, and qualification status',
  },
  {
    code: 'referral.manage',
    module: 'referrals',
    action: 'manage',
    category: 'REFERRAL',
    displayName: 'Manage Referrals',
    description: 'Can create referral campaigns and cancel referrals',
  },
  {
    code: 'referral.configuration.manage',
    module: 'referrals',
    action: 'manage',
    category: 'REFERRAL',
    displayName: 'Manage Referral Configuration',
    description: 'Can configure expiry, max uses, and qualification timeouts',
  },
  {
    code: 'referral.audit.view',
    module: 'referrals',
    action: 'view',
    category: 'REFERRAL',
    displayName: 'View Referral Audit',
    description: 'Can read the referral audit trail',
  },
  {
    code: 'referral.statistics.view',
    module: 'referrals',
    action: 'view',
    category: 'REFERRAL',
    displayName: 'View Referral Statistics',
    description: 'Can view conversion rates and campaign performance',
  },

  // Notification Center (Phase 19)
  {
    code: 'notification.view',
    module: 'notification',
    action: 'view',
    category: 'NOTIFICATION',
    displayName: 'View Notifications',
    description: 'Can view notifications and inbox entries',
  },
  {
    code: 'notification.manage',
    module: 'notification',
    action: 'manage',
    category: 'NOTIFICATION',
    displayName: 'Manage Notifications',
    description: 'Can send, schedule, and delete notifications',
  },
  {
    code: 'announcement.manage',
    module: 'notification',
    action: 'manage',
    category: 'NOTIFICATION',
    displayName: 'Manage Announcements',
    description: 'Can publish platform, country, and region announcements',
  },
  {
    code: 'notification.configuration.manage',
    module: 'notification',
    action: 'manage',
    category: 'NOTIFICATION',
    displayName: 'Manage Notification Configuration',
    description: 'Can configure retries, retention, batch size, and channels',
  },
  {
    code: 'notification.audit.view',
    module: 'notification',
    action: 'view',
    category: 'NOTIFICATION',
    displayName: 'View Notification Audit',
    description: 'Can read the notification audit trail',
  },
  {
    code: 'notification.statistics.view',
    module: 'notification',
    action: 'view',
    category: 'NOTIFICATION',
    displayName: 'View Notification Statistics',
    description: 'Can view delivery, read, and failure rates',
  },

  // Reports & Analytics Engine (Phase 20)
  {
    code: 'analytics.manage',
    module: 'analytics',
    action: 'manage',
    category: 'ANALYTICS',
    displayName: 'Manage Analytics',
    description: 'Can define reports, dashboards, and metric snapshots',
  },
  {
    code: 'analytics.export',
    module: 'analytics',
    action: 'export',
    category: 'ANALYTICS',
    displayName: 'Export Analytics',
    description: 'Can export reports to CSV, Excel, PDF, or JSON',
  },
  {
    code: 'analytics.configuration.manage',
    module: 'analytics',
    action: 'manage',
    category: 'ANALYTICS',
    displayName: 'Manage Analytics Configuration',
    description: 'Can configure snapshot intervals, retention, and export limits',
  },
  {
    code: 'analytics.audit.view',
    module: 'analytics',
    action: 'view',
    category: 'ANALYTICS',
    displayName: 'View Analytics Audit',
    description: 'Can read the analytics audit trail',
  },
  {
    code: 'analytics.statistics.view',
    module: 'analytics',
    action: 'view',
    category: 'ANALYTICS',
    displayName: 'View Analytics Statistics',
    description: 'Can view platform KPI and growth metric summaries',
  },

  {
    code: 'dashboard.financial.view',
    module: 'admin_dashboard',
    action: 'view',
    category: 'DASHBOARD',
    displayName: 'View Financial Dashboards',
    description: 'Treasury, wallet, revenue, withdrawal and settlement dashboards',
  },
  {
    code: 'dashboard.operations.view',
    module: 'admin_dashboard',
    action: 'view',
    category: 'DASHBOARD',
    displayName: 'View Operations Dashboards',
    description: 'Platform overview, users, events, tasks, notifications and analytics',
  },
  {
    code: 'dashboard.engagement.view',
    module: 'admin_dashboard',
    action: 'view',
    category: 'DASHBOARD',
    displayName: 'View Engagement Dashboards',
    description: 'Gifts, treasure, family, VIP, level, ranking and referral dashboards',
  },
  {
    code: 'dashboard.moderation.view',
    module: 'admin_dashboard',
    action: 'view',
    category: 'DASHBOARD',
    displayName: 'View Moderation Dashboards',
    description: 'Moderation queue and operational audit logs',
  },
  {
    code: 'user.location.view',
    module: 'organization',
    action: 'view',
    category: 'USER',
    displayName: 'View User Location',
    description: "Read a user's assigned country, state and region",
  },
  {
    code: 'user.location.assign',
    module: 'organization',
    action: 'assign',
    category: 'USER',
    displayName: 'Assign User Location',
    description: "Set a user's country, state and region for geographic scoping",
  },
  // Role approval chains (Official → Manager → Admin)
  {
    code: 'role_request.submit',
    module: 'role_requests',
    action: 'submit',
    category: 'SYSTEM',
    displayName: 'Submit Role Request',
    description: 'File a role application on behalf of a user',
  },
  {
    code: 'role_request.view',
    module: 'role_requests',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Role Request',
    description: 'Read a role request and its audit trail',
  },
  {
    code: 'role_request.review',
    module: 'role_requests',
    action: 'review',
    category: 'SYSTEM',
    displayName: 'Review Role Request',
    description: 'Advance or send back a request at your stage and territory',
  },
  {
    code: 'role_request.decide',
    module: 'role_requests',
    action: 'decide',
    category: 'SYSTEM',
    displayName: 'Decide Role Request',
    description: 'Approve (granting the role) or reject a request',
  },
  // Mobile operational surfaces (non-staff roles; scope-narrowed)
  {
    code: 'mobile.workforce.view',
    module: 'mobile',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'Mobile Workforce Console',
    description: 'Scoped population, user list and moderation queue on mobile',
  },
  {
    code: 'mobile.partner.view',
    module: 'mobile',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'Mobile Partner Console',
    description: 'Own agency, coin-seller or host earnings on mobile',
  },
  // Business Admin Dashboard (Phase 21)
  {
    code: 'dashboard.view',
    module: 'admin_dashboard',
    action: 'view',
    category: 'DASHBOARD',
    displayName: 'View Dashboard',
    description: 'Can open the operational dashboard and its widgets',
  },
  {
    code: 'dashboard.manage',
    module: 'admin_dashboard',
    action: 'manage',
    category: 'DASHBOARD',
    displayName: 'Manage Dashboard',
    description: 'Can manage widgets, layouts, and operational alerts',
  },
  {
    code: 'dashboard.export',
    module: 'admin_dashboard',
    action: 'export',
    category: 'DASHBOARD',
    displayName: 'Export Dashboard',
    description: 'Can export dashboard data to CSV, Excel, PDF, or JSON',
  },
  {
    code: 'dashboard.configuration.manage',
    module: 'admin_dashboard',
    action: 'manage',
    category: 'DASHBOARD',
    displayName: 'Manage Dashboard Configuration',
    description: 'Can configure refresh interval, widget limits, and cache TTL',
  },
  {
    code: 'dashboard.audit.view',
    module: 'admin_dashboard',
    action: 'view',
    category: 'DASHBOARD',
    displayName: 'View Dashboard Audit',
    description: 'Can read the dashboard audit trail',
  },
  {
    code: 'dashboard.statistics.view',
    module: 'admin_dashboard',
    action: 'view',
    category: 'DASHBOARD',
    displayName: 'View Dashboard Statistics',
    description: 'Can view dashboard usage and health statistics',
  },

  // Review permissions for the official portal. These are enforced by
  // controllers but were never declared here, which left every one of those
  // endpoints reachable only by the SUPER_ADMIN wildcard — no other role could
  // be granted a code the catalogue does not define.
  {
    code: 'content_request.review',
    module: 'content_request',
    action: 'review',
    category: 'SYSTEM',
    displayName: 'Review Content Requests',
    description: 'Review, approve or reject creator content requests',
  },
  {
    code: 'support_ticket.review',
    module: 'support_ticket',
    action: 'review',
    category: 'SYSTEM',
    displayName: 'Review Support Tickets',
    description: 'View, assign and respond to support tickets in scope',
  },
  {
    code: 'moderator.warning.review',
    module: 'moderator_warning',
    action: 'review',
    category: 'SYSTEM',
    displayName: 'Review Moderator Warnings',
    description: 'Review and action internal moderator warning records',
  },

  // Moderator Workforce & Operational System Permissions
  {
    code: 'moderator.shift.view',
    module: 'moderator_shift',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Shift',
    description: 'View own or assigned shift',
  },
  {
    code: 'moderator.shift.manage',
    module: 'moderator_shift',
    action: 'manage',
    category: 'SYSTEM',
    displayName: 'Manage Shift',
    description: 'Assign or edit moderator working shifts',
  },
  {
    code: 'moderator.device.request',
    module: 'moderator_device',
    action: 'request',
    category: 'SYSTEM',
    displayName: 'Request Device Change',
    description: 'Submit request to replace bound physical device',
  },
  {
    code: 'moderator.device.review',
    module: 'moderator_device',
    action: 'review',
    category: 'SYSTEM',
    displayName: 'Review Device Change',
    description: 'Manager-stage review of a moderator device change request',
  },
  {
    code: 'moderator.device.approve',
    module: 'moderator_device',
    action: 'approve',
    category: 'SYSTEM',
    displayName: 'Approve Device Change',
    description: 'Final approval of a manager-reviewed moderator device change request',
  },
  {
    code: 'investigation.recording.view',
    module: 'investigation_recording',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Investigation Recording',
    description: 'View server-side evidence packages and audit recordings',
  },
  {
    code: 'moderator.warning.issue',
    module: 'moderator_warning',
    action: 'issue',
    category: 'SYSTEM',
    displayName: 'Issue Moderator Warning',
    description: 'Issue internal warnings (Level 1-3) to moderators',
  },
  {
    code: 'moderator.warning.view',
    module: 'moderator_warning',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Moderator Warnings',
    description: 'View warning records across moderators',
  },
  {
    code: 'moderator.warning.view.self',
    module: 'moderator_warning',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Own Warnings',
    description: 'View own warning records',
  },
  {
    code: 'moderator.warning.resolve',
    module: 'moderator_warning',
    action: 'resolve',
    category: 'SYSTEM',
    displayName: 'Resolve Warning',
    description: 'Resolve moderator warnings and restore access',
  },
  {
    code: 'moderator.performance.view.self',
    module: 'moderator_performance',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Own Performance',
    description: 'View own daily performance stats and score',
  },
  {
    code: 'moderator.performance.view.all',
    module: 'moderator_performance',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View All Moderator Performance',
    description: 'View KPI performance summary across all moderators',
  },
  {
    code: 'live.stream.create',
    module: 'live_stream',
    action: 'create',
    category: 'ROOM',
    displayName: 'Create Live Stream',
    description: 'Host creates a new live stream',
  },
  {
    code: 'live.stream.view',
    module: 'live_stream',
    action: 'view',
    category: 'ROOM',
    displayName: 'View Live Stream',
    description: 'View active live stream details',
  },
  {
    code: 'live.stream.manage',
    module: 'live_stream',
    action: 'manage',
    category: 'ROOM',
    displayName: 'Manage Live Stream',
    description: 'End or close a live stream',
  },
  {
    code: 'live.stream.moderate',
    module: 'live_stream',
    action: 'moderate',
    category: 'ROOM',
    displayName: 'Moderate Live Stream',
    description: 'Warn, mute, kick, or ban users in a live stream',
  },
  {
    code: 'task.assign.moderator',
    module: 'tasks',
    action: 'assign',
    category: 'TASK',
    displayName: 'Assign Task to Moderator',
    description: 'Official/Manager assigns operational tasks to moderators',
  },
  {
    code: 'task.view.assigned',
    module: 'tasks',
    action: 'view',
    category: 'TASK',
    displayName: 'View Assigned Tasks',
    description: 'Moderator views and updates tasks assigned to them',
  },
  {
    code: 'moderation.action.approve',
    module: 'moderation_approval',
    action: 'approve',
    category: 'SYSTEM',
    displayName: 'Approve Moderation Action',
    description: 'Approve or reject a moderator-proposed ban before it executes',
  },
  {
    code: 'post.moderate',
    module: 'posts',
    action: 'moderate',
    category: 'POST',
    displayName: 'Moderate Posts',
    description: 'Delete any user post or comment',
  },
];

// Data-Driven Default Role Hierarchy Edges (parent -> child)
export const DEFAULT_ROLE_HIERARCHY: Array<{ parent: SystemRoleType; child: SystemRoleType }> = [
  { parent: 'SUPER_ADMIN', child: 'ADMIN' },
  { parent: 'ADMIN', child: 'COUNTRY_MANAGER' },
  { parent: 'ADMIN', child: 'BUSINESS_DEVELOPMENT' },
  { parent: 'COUNTRY_MANAGER', child: 'OFFICIAL' },
  { parent: 'OFFICIAL', child: 'MODERATOR' },
  { parent: 'OFFICIAL', child: 'AGENCY' },
  { parent: 'OFFICIAL', child: 'COIN_SELLER' },
  { parent: 'MODERATOR', child: 'HOST' },
  { parent: 'HOST', child: 'USER' },
];

// Default Role to Permissions Initial Mapping
/**
 * Member-facing permissions — every platform account holds these. They guard
 * only self-scoped routes; nothing here reaches an administrative surface.
 */
const MEMBER_PERMISSIONS = [
  'gift.send',
  'gift.history.view',
  'family.view',
  'family.create',
  'family.update',
  'family.member.manage',
  'family.role.manage',
  'wealth.view',
  'level.view',
  'achievement.view',
  'ranking.view',
  'event.view',
  'task.view',
  'referral.view',
  'notification.view',
  'withdrawal.request',
  // Self-scoped: this files an application for yourself (agency, coin seller…).
  // Reviewing and deciding those applications stay operational permissions —
  // `role_request.view`/`review`/`decide` are deliberately not here, so a member
  // can apply but cannot see or action anyone's queue, including their own.
  'role_request.submit',
];

/**
 * Role → permission matrix, derived from the PRD "Soulzaaa Authority Matrix"
 * and the Restrictions section of each role specification.
 *
 * Rule of thumb when extending: a permission that guards a platform-wide
 * (cross-user) route belongs to operational roles only. Self-scoped routes
 * belong in MEMBER_PERMISSIONS. `rbac-role-matrix.spec.ts` enforces both.
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<SystemRoleType, string[]> = {
  // Highest authority — resolved through a wildcard, see PermissionResolverService.
  SUPER_ADMIN: ['*'],

  /**
   * Operations head. Authority Matrix grants every operational module but
   * withholds platform security, global settings, revenue sharing, coin
   * pricing, VIP pricing, payment gateways, maintenance mode and shutdown.
   */
  ADMIN: [
    ...MEMBER_PERMISSIONS,
    // User & creator management
    'user.view',
    'user.update',
    'user.ban',
    'user.delete',
    'user.list.view',
    'user.profile.view',
    'user.audit.view',
    'user.role.assign',
    'user.location.view',
    'user.location.assign',
    // `role_request.submit` arrives via MEMBER_PERMISSIONS.
    'role_request.view',
    'role_request.review',
    'role_request.decide',
    // An Official escalating a support ticket hands the case to the Admin
    // portal, so an Admin must be able to reach the same queue the Official
    // reviews it in — otherwise escalation drops the ticket into a queue
    // nobody can open.
    'support_ticket.review',
    'user.role.remove',
    'user.role.update',
    'user.status.activate',
    'user.status.suspend',
    'user.status.lock',
    'user.status.unlock',
    'user.session.force_logout',
    // Workforce (Manager / Official / Moderator / BD management)
    'workforce.list.view',
    'workforce.detail.view',
    'workforce.hierarchy.view',
    'workforce.assign',
    'workforce.transfer',
    'workforce.status.manage',
    'organization.hierarchy.view',
    // Agency & Coin Seller management
    'agency.create',
    'agency.approve',
    'agency.reject',
    'agency.settlement.view',
    'agency.settlement.history.view',
    'agency.settlement.audit.view',
    'seller.approve',
    'seller.reject',
    'coin_seller.settlement.view',
    'coin_seller.settlement.history.view',
    'coin_seller.settlement.audit.view',
    'coin_seller.settlement.configuration.manage',
    'coin_seller.inventory.approve',
    // Room & stream moderation
    'room.create',
    'room.update',
    'room.close',
    'room.delete',
    'room.mute',
    // Content management
    'gift.manage',
    'gift.catalog.view',
    'gift.transaction.view',
    'gift.audit.view',
    'game.manage',
    // Wealth Level: ADMIN may manage tiers/benefits/rewards and view
    // audit/statistics, but NOT the downgrade policy or general module
    // configuration — those are SUPER_ADMIN-only (granted via the '*'
    // wildcard). The legacy VIP module's identical split (manage granted,
    // configuration withheld) was the precedent for this design.
    'wealth.manage',
    'wealth.statistics.view',
    'wealth.audit.view',
    'badge.manage',
    'achievement.manage',
    'achievement.configuration.manage',
    'achievement.audit.view',
    'achievement.statistics.view',
    'treasure.configuration.manage',
    // Events & tasks
    'event.create',
    'event.publish',
    'event.submit_for_approval',
    'event.manage',
    'event.configuration.manage',
    'event.audit.view',
    'event.statistics.view',
    'task.manage',
    'task.configuration.manage',
    'task.audit.view',
    'task.statistics.view',
    // Content moderation
    'post.moderate',
    // Progression & rankings
    'level.manage',
    'level.configuration.manage',
    'level.audit.view',
    'level.statistics.view',
    'ranking.manage',
    'ranking.configuration.manage',
    'ranking.audit.view',
    'ranking.statistics.view',
    // Family oversight
    'family.delete',
    'family.audit.view',
    'family.statistics.view',
    // Referrals
    'referral.manage',
    'referral.configuration.manage',
    'referral.audit.view',
    'referral.statistics.view',
    // Wallet operations — adjustment allowed within Super Admin-granted limits
    'wallet.view',
    'wallet.adjust',
    'wallet.balance.view',
    'wallet.transaction.view',
    'wallet.reservation.view',
    'wallet.audit.view',
    // Operational financial reporting & refund approval
    'purchase.package.view',
    'purchase.order.view',
    'purchase.audit.view',
    'purchase.verify',
    'revenue.view',
    'revenue.history.view',
    'revenue.audit.view',
    'withdrawal.view',
    'withdrawal.history.view',
    'withdrawal.approve',
    'withdrawal.audit.view',
    // Treasury — Authority Matrix: view only
    'treasury.summary.view',
    'treasury.economy.view',
    'treasury.health.view',
    'treasury.policies.view',
    'treasury.risk.view',
    'treasury.audit.view',
    // Platform settings — Authority Matrix: view only
    'config.settings.view',
    'config.flags.view',
    'config.history.view',
    // Notifications & announcements (operational scope)
    'notification.manage',
    'notification.configuration.manage',
    'notification.audit.view',
    'notification.statistics.view',
    'announcement.manage',
    // Moderator Warnings (Task 18)
    'moderator.warning.issue',
    'moderator.warning.resolve',
    // Moderator device change — Admin can act as Manager-stage reviewer too
    // when needed, but the final approve stage is Admin-exclusive (spec:
    // "Approved only by Admin"); see moderator.device.approve below.
    'moderator.device.review',
    'moderator.device.approve',
    'moderation.action.approve',
    // Analytics, dashboard & audit (operational scope)
    'analytics.view',
    'analytics.manage',
    'analytics.export',
    'analytics.audit.view',
    'analytics.statistics.view',
    'dashboard.view',
    'dashboard.financial.view',
    'dashboard.operations.view',
    'dashboard.engagement.view',
    'dashboard.moderation.view',
    'dashboard.manage',
    'dashboard.export',
    'dashboard.audit.view',
    'dashboard.statistics.view',
    'audit.view',
    // Investigation recordings (Task 30)
    'investigation.recording.view',
    // Moderator provisioning — Admins can create hidden Moderator accounts directly
    'admin.identity.manage',
  ],

  /**
   * Country-level operations. Manages Officials, reviews regional reports and
   * country revenue, approves regional events. Approval of Agencies and Coin
   * Sellers is reserved for Admin — the Manager only reviews.
   */
  COUNTRY_MANAGER: [
    ...MEMBER_PERMISSIONS,
    'mobile.workforce.view',
    'user.location.view',
    'role_request.view',
    'role_request.review',
    'role_request.decide',
    'user.view',
    'user.update',
    'user.list.view',
    'user.profile.view',
    'moderator.device.review',
    'moderator.warning.review',
    'workforce.list.view',
    // workforce.detail.view intentionally omitted — spec: Admin/Super Admin only (Task 36)
    'workforce.hierarchy.view',
    'workforce.assign',
    'workforce.transfer',
    'workforce.status.manage',
    'organization.hierarchy.view',
    'agency.settlement.view',
    'agency.settlement.history.view',
    'coin_seller.settlement.view',
    'coin_seller.settlement.history.view',
    'event.create',
    'event.publish',
    'event.submit_for_approval',
    'task.manage',
    'revenue.view',
    'revenue.history.view',
    'analytics.view',
    'analytics.statistics.view',
    'ranking.view',
    'family.statistics.view',
    'notification.manage',
    // audit.view intentionally omitted — spec: Admin/Super Admin only (Task 29)
  ],

  /**
   * Regional representative. Verifies, recommends and coordinates — it cannot
   * approve roles, ban users, touch wallets or approve withdrawals.
   */
  OFFICIAL: [
    ...MEMBER_PERMISSIONS,
    'mobile.workforce.view',
    'user.location.view',
    'role_request.view',
    'role_request.review',
    'content_request.review',
    'support_ticket.review',
    'moderation.action.approve',
    'user.view',
    'user.update',
    'user.list.view',
    'user.profile.view',
    'organization.hierarchy.view',
    'workforce.list.view',
    // workforce.detail.view intentionally omitted — spec: Admin/Super Admin only (Task 36)
    'agency.settlement.view',
    'agency.settlement.history.view',
    'coin_seller.settlement.view',
    'coin_seller.settlement.history.view',
    'event.view',
    'event.create',
    'event.manage',
    'task.manage',
    'analytics.view',
    'ranking.view',
    'family.statistics.view',
    'notification.manage',
  ],

  /**
   * Anonymous enforcement role. Moderation actions only — no financial
   * visibility, no role approvals, and it cannot lock or close rooms.
   */
  MODERATOR: [
    ...MEMBER_PERMISSIONS,
    'mobile.workforce.view',
    'user.location.view',
    'user.view',
    'user.list.view',
    'user.profile.view',
    'user.ban',
    'room.update',
    'room.mute',
    'post.moderate',
    'moderator.shift.view',
    'moderator.device.request',
    'moderator.warning.view.self',
    'moderator.performance.view.self',
    'live.stream.view',
    'live.stream.moderate',
    'task.view.assigned',
  ],

  /** Recruits agencies and hosts; approval stays with Admin. */
  BUSINESS_DEVELOPMENT: [
    ...MEMBER_PERMISSIONS,
    'user.view',
    'user.list.view',
    'agency.create',
    'agency.settlement.view',
    'coin_seller.settlement.view',
    'analytics.view',
    'analytics.statistics.view',
    'ranking.view',
  ],

  /** Business partner managing its own community. Reads its own settlements only. */
  AGENCY: [
    ...MEMBER_PERMISSIONS,
    'mobile.partner.view',
    'user.view',
    'room.create',
    'agency.settlement.view',
    'agency.settlement.history.view',
    // Authors events and submits them for approval. Deliberately NOT
    // 'event.publish' or 'event.manage': making an event live is the
    // Official/Admin half of the workflow.
    'event.create',
    'event.submit_for_approval',
  ],

  /** Coin Seller permission set, activated inside an existing Agency account. */
  COIN_SELLER: [
    ...MEMBER_PERMISSIONS,
    'mobile.partner.view',
    'coin_seller.settlement.view',
    'coin_seller.settlement.history.view',
    'coin_seller.inventory.purchase',
    'coin_seller.inventory.sell',
  ],

  /** Creator. Runs rooms and streams; earnings are read through self-scoped routes. */
  HOST: [...MEMBER_PERMISSIONS, 'mobile.partner.view', 'room.create', 'room.update'],

  /** Platform participant. */
  USER: [...MEMBER_PERMISSIONS, 'room.create'],
};
