// Platform Default System Roles
export const SYSTEM_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  COUNTRY_MANAGER: 'COUNTRY_MANAGER',
  OFFICIAL: 'OFFICIAL',
  MODERATOR: 'MODERATOR',
  BUSINESS_DEVELOPMENT: 'BUSINESS_DEVELOPMENT',
  AGENCY: 'AGENCY',
  COIN_SELLER: 'COIN_SELLER',
  HOST: 'HOST',
  USER: 'USER',
} as const;

export type SystemRoleType = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

// Permission Categories
export const PERMISSION_CATEGORIES = [
  'USER',
  'ROOM',
  'AUDIO_ROOM',
  'VIDEO_ROOM',
  'WALLET',
  'GIFTS',
  'COIN',
  'VIP',
  'FAMILY',
  'GAME',
  'EVENT',
  'ANALYTICS',
  'AGENCY',
  'COIN_SELLER',
  'SYSTEM',
] as const;

export type PermissionCategory = (typeof PERMISSION_CATEGORIES)[number];

// Standard Granular Permissions across all Soulzaa Platform Modules
export const DEFAULT_PERMISSIONS = [
  // Enterprise Gift Engine (Phase 5)
  {
    code: 'gift.catalog.view',
    module: 'gifts',
    action: 'view',
    category: 'ROOM',
    displayName: 'View Gift Catalog',
    description: 'Can view and manage gift catalog and categories',
  },
  {
    code: 'gift.send',
    module: 'gifts',
    action: 'send',
    category: 'ROOM',
    displayName: 'Send Gift',
    description: 'Can send gifts in audio/video rooms, PK battles, and chats',
  },
  {
    code: 'gift.history.view',
    module: 'gifts',
    action: 'view',
    category: 'ROOM',
    displayName: 'View Gift History',
    description: 'Can view gift transaction history and logs',
  },
  {
    code: 'gift.audit.view',
    module: 'gifts',
    action: 'view',
    category: 'ROOM',
    displayName: 'View Gift Audit',
    description: 'Can view gift operational audit trail',
  },

  // Coin Purchase & Payment Infrastructure (Phase 4)
  {
    code: 'purchase.package.view',
    module: 'payments',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Coin Packages',
    description: 'Can view and manage purchasable coin packages catalog',
  },
  {
    code: 'purchase.order.view',
    module: 'payments',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Purchase Orders',
    description: 'Can view purchase order history and verification status',
  },
  {
    code: 'purchase.audit.view',
    module: 'payments',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Purchase Audit',
    description: 'Can view purchase verification and order audit trail',
  },
  {
    code: 'purchase.verify',
    module: 'payments',
    action: 'verify',
    category: 'WALLET',
    displayName: 'Verify Purchases',
    description: 'Can verify IAP receipts and trigger manual re-verifications',
  },

  // Enterprise Wallet & Double-Entry Ledger (Phase 3)
  {
    code: 'wallet.view',
    module: 'wallet',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Wallet Accounts',
    description: 'Can view platform wallet accounts and metrics',
  },
  {
    code: 'wallet.balance.view',
    module: 'wallet',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Wallet Balances',
    description: 'Can view detailed wallet balance projections and reconciliations',
  },
  {
    code: 'wallet.transaction.view',
    module: 'wallet',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Wallet Transactions',
    description: 'Can view wallet transactions and immutable ledger entries',
  },
  {
    code: 'wallet.reservation.view',
    module: 'wallet',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Wallet Reservations',
    description: 'Can view active and historical coin reservation holds',
  },
  {
    code: 'wallet.audit.view',
    module: 'wallet',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Wallet Audit',
    description: 'Can view wallet audit history logs',
  },

  // Super Admin Treasury & Coin Economy Governance (Phase 2E)
  {
    code: 'treasury.summary.view',
    module: 'treasury',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Treasury Summary',
    description: 'Can view treasury reserve balances and coin supply stats',
  },
  {
    code: 'treasury.economy.view',
    module: 'treasury',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Economy Breakdown',
    description: 'Can view coin circulating, reserved, and max supply metrics',
  },
  {
    code: 'treasury.health.view',
    module: 'treasury',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Financial Health',
    description: 'Can view reserve ratio and financial health indicators',
  },
  {
    code: 'treasury.policies.view',
    module: 'treasury',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Financial Policies',
    description: 'Can view financial limit policies and threshold bounds',
  },
  {
    code: 'treasury.policies.update',
    module: 'treasury',
    action: 'update',
    category: 'WALLET',
    displayName: 'Update Financial Policies',
    description: 'Can modify financial limit policies and threshold bounds',
  },
  {
    code: 'treasury.risk.view',
    module: 'treasury',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Risk Controls',
    description: 'Can view financial emergency freeze and risk control flags',
  },
  {
    code: 'treasury.risk.manage',
    module: 'treasury',
    action: 'manage',
    category: 'WALLET',
    displayName: 'Manage Risk Controls',
    description: 'Can execute emergency freeze or resume on financial features',
  },
  {
    code: 'treasury.audit.view',
    module: 'treasury',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Treasury Audit',
    description: 'Can view treasury operational audit trail',
  },

  // Super Admin Platform Configuration & Global Settings (Phase 2D)
  {
    code: 'config.settings.view',
    module: 'config',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Settings',
    description: 'Can view global platform settings and categories',
  },
  {
    code: 'config.settings.update',
    module: 'config',
    action: 'update',
    category: 'SYSTEM',
    displayName: 'Update Setting',
    description: 'Can modify global platform settings',
  },
  {
    code: 'config.settings.reset',
    module: 'config',
    action: 'reset',
    category: 'SYSTEM',
    displayName: 'Reset Setting',
    description: 'Can reset platform setting to default value',
  },
  {
    code: 'config.flags.view',
    module: 'config',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Feature Flags',
    description: 'Can view platform feature flag statuses',
  },
  {
    code: 'config.flags.manage',
    module: 'config',
    action: 'manage',
    category: 'SYSTEM',
    displayName: 'Manage Feature Flags',
    description: 'Can enable, disable, or toggle feature flags',
  },
  {
    code: 'config.history.view',
    module: 'config',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Config History',
    description: 'Can view platform configuration change audit history',
  },

  // Super Admin Workforce & Operational Personnel Management (Phase 2C)
  {
    code: 'workforce.list.view',
    module: 'workforce',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Workforce List',
    description: 'Can view and search operational workforce personnel',
  },
  {
    code: 'workforce.detail.view',
    module: 'workforce',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Workforce Details',
    description: 'Can view operational status, workload summary, and assignment history',
  },
  {
    code: 'workforce.assign',
    module: 'workforce',
    action: 'assign',
    category: 'SYSTEM',
    displayName: 'Assign Workforce',
    description: 'Can assign operational scope to personnel',
  },
  {
    code: 'workforce.transfer',
    module: 'workforce',
    action: 'transfer',
    category: 'SYSTEM',
    displayName: 'Transfer Workforce',
    description: 'Can transfer or reassign operational personnel scope',
  },
  {
    code: 'workforce.status.manage',
    module: 'workforce',
    action: 'manage',
    category: 'SYSTEM',
    displayName: 'Manage Workforce Status',
    description: 'Can activate, deactivate, suspend, or restore personnel operational status',
  },
  {
    code: 'workforce.hierarchy.view',
    module: 'workforce',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Reporting Hierarchy',
    description: 'Can view full operational reporting hierarchy graph',
  },

  // Super Admin Organization & Geographic Management
  {
    code: 'organization.country.manage',
    module: 'organization',
    action: 'manage',
    category: 'SYSTEM',
    displayName: 'Manage Countries',
    description: 'Can create, update, activate and deactivate countries',
  },
  {
    code: 'organization.state.manage',
    module: 'organization',
    action: 'manage',
    category: 'SYSTEM',
    displayName: 'Manage States',
    description: 'Can create, update, activate and deactivate states',
  },
  {
    code: 'organization.region.manage',
    module: 'organization',
    action: 'manage',
    category: 'SYSTEM',
    displayName: 'Manage Regions',
    description: 'Can create, update, activate and deactivate regions',
  },
  {
    code: 'organization.manager.assign',
    module: 'organization',
    action: 'assign',
    category: 'SYSTEM',
    displayName: 'Assign Country Managers',
    description: 'Can assign, transfer, or remove Country Managers',
  },
  {
    code: 'organization.hierarchy.view',
    module: 'organization',
    action: 'view',
    category: 'SYSTEM',
    displayName: 'View Organization Hierarchy',
    description: 'Can view complete organizational hierarchy graph',
  },

  // User Management
  {
    code: 'user.view',
    module: 'user',
    action: 'view',
    category: 'USER',
    displayName: 'View Users',
    description: 'Can view user profile details and list users',
  },
  {
    code: 'user.update',
    module: 'user',
    action: 'update',
    category: 'USER',
    displayName: 'Update User',
    description: 'Can update user profiles and account details',
  },
  {
    code: 'user.ban',
    module: 'user',
    action: 'ban',
    category: 'USER',
    displayName: 'Ban User',
    description: 'Can suspend or ban user accounts',
  },
  {
    code: 'user.delete',
    module: 'user',
    action: 'delete',
    category: 'USER',
    displayName: 'Delete User',
    description: 'Can soft or hard delete user accounts',
  },

  // Wallet & Financial
  {
    code: 'wallet.view',
    module: 'wallet',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Wallet',
    description: 'Can view wallet balances and transactions',
  },
  {
    code: 'wallet.adjust',
    module: 'wallet',
    action: 'adjust',
    category: 'WALLET',
    displayName: 'Adjust Wallet',
    description: 'Can credit/debit user balances manually',
  },

  // Audio & Video Rooms
  {
    code: 'room.create',
    module: 'room',
    action: 'create',
    category: 'ROOM',
    displayName: 'Create Room',
    description: 'Can create audio/video rooms',
  },
  {
    code: 'room.update',
    module: 'room',
    action: 'update',
    category: 'ROOM',
    displayName: 'Update Room',
    description: 'Can update room settings and metadata',
  },
  {
    code: 'room.close',
    module: 'room',
    action: 'close',
    category: 'ROOM',
    displayName: 'Close Room',
    description: 'Can forcefully close audio/video rooms',
  },
  {
    code: 'room.delete',
    module: 'room',
    action: 'delete',
    category: 'ROOM',
    displayName: 'Delete Room',
    description: 'Can delete room records',
  },
  {
    code: 'room.mute',
    module: 'room',
    action: 'mute',
    category: 'ROOM',
    displayName: 'Mute Room User',
    description: 'Can mute users in audio/video rooms',
  },

  // Agency Portal & Management
  {
    code: 'agency.create',
    module: 'agency',
    action: 'create',
    category: 'AGENCY',
    displayName: 'Create Agency',
    description: 'Can create new host/talent agencies',
  },
  {
    code: 'agency.approve',
    module: 'agency',
    action: 'approve',
    category: 'AGENCY',
    displayName: 'Approve Agency',
    description: 'Can approve agency registration requests',
  },
  {
    code: 'agency.reject',
    module: 'agency',
    action: 'reject',
    category: 'AGENCY',
    displayName: 'Reject Agency',
    description: 'Can reject agency registration requests',
  },

  // Coin Seller
  {
    code: 'seller.approve',
    module: 'seller',
    action: 'approve',
    category: 'COIN_SELLER',
    displayName: 'Approve Coin Seller',
    description: 'Can approve coin seller applications',
  },
  {
    code: 'seller.reject',
    module: 'seller',
    action: 'reject',
    category: 'COIN_SELLER',
    displayName: 'Reject Coin Seller',
    description: 'Can reject coin seller applications',
  },

  // Events
  {
    code: 'event.create',
    module: 'event',
    action: 'create',
    category: 'EVENT',
    displayName: 'Create Event',
    description: 'Can create platform events',
  },
  {
    code: 'event.publish',
    module: 'event',
    action: 'publish',
    category: 'EVENT',
    displayName: 'Publish Event',
    description: 'Can publish scheduled events',
  },

  // Analytics
  {
    code: 'analytics.view',
    module: 'analytics',
    action: 'view',
    category: 'ANALYTICS',
    displayName: 'View Analytics',
    description: 'Can view platform analytics and operational metrics',
  },

  // Module Management
  {
    code: 'gift.manage',
    module: 'gift',
    action: 'manage',
    category: 'GIFTS',
    displayName: 'Manage Gifts',
    description: 'Can configure virtual gifts and pricing',
  },
  {
    code: 'coin.manage',
    module: 'coin',
    action: 'manage',
    category: 'COIN',
    displayName: 'Manage Coins',
    description: 'Can manage coin rates, packages, and distributions',
  },
  {
    code: 'game.manage',
    module: 'game',
    action: 'manage',
    category: 'GAME',
    displayName: 'Manage Games',
    description: 'Can configure platform mini-games and rules',
  },
  {
    code: 'vip.manage',
    module: 'vip',
    action: 'manage',
    category: 'VIP',
    displayName: 'Manage VIP',
    description: 'Can manage VIP tiers, perks, and subscriptions',
  },
];

// Data-Driven Default Role Hierarchy Edges (parent -> child)
export const DEFAULT_ROLE_HIERARCHY: Array<{ parent: SystemRoleType; child: SystemRoleType }> = [
  { parent: 'SUPER_ADMIN', child: 'ADMIN' },
  { parent: 'ADMIN', child: 'COUNTRY_MANAGER' },
  { parent: 'ADMIN', child: 'BUSINESS_DEVELOPMENT' },
  { parent: 'COUNTRY_MANAGER', child: 'OFFICIAL' },
  { parent: 'OFFICIAL', child: 'MODERATOR' },
  { parent: 'OFFICIAL', child: 'AGENCY' },
  { parent: 'OFFICIAL', child: 'COIN_SELLER' },
  { parent: 'MODERATOR', child: 'HOST' },
  { parent: 'HOST', child: 'USER' },
];

// Default Role to Permissions Initial Mapping
export const DEFAULT_ROLE_PERMISSIONS: Record<SystemRoleType, string[]> = {
  SUPER_ADMIN: ['*'],
  ADMIN: [
    'user.view',
    'user.update',
    'user.ban',
    'user.delete',
    'wallet.view',
    'wallet.adjust',
    'room.create',
    'room.update',
    'room.close',
    'room.delete',
    'room.mute',
    'agency.create',
    'agency.approve',
    'agency.reject',
    'seller.approve',
    'seller.reject',
    'event.create',
    'event.publish',
    'analytics.view',
    'gift.manage',
    'coin.manage',
    'game.manage',
    'vip.manage',
  ],
  COUNTRY_MANAGER: [
    'user.view',
    'user.update',
    'user.ban',
    'wallet.view',
    'room.create',
    'room.update',
    'room.close',
    'room.mute',
    'agency.create',
    'agency.approve',
    'agency.reject',
    'seller.approve',
    'seller.reject',
    'event.create',
    'event.publish',
    'analytics.view',
  ],
  OFFICIAL: [
    'user.view',
    'user.update',
    'user.ban',
    'room.create',
    'room.update',
    'room.close',
    'room.mute',
    'agency.approve',
    'agency.reject',
    'seller.approve',
    'seller.reject',
    'event.create',
  ],
  MODERATOR: ['user.view', 'user.ban', 'room.update', 'room.close', 'room.mute'],
  BUSINESS_DEVELOPMENT: [
    'user.view',
    'agency.create',
    'agency.approve',
    'seller.approve',
    'analytics.view',
  ],
  AGENCY: ['user.view', 'room.create'],
  COIN_SELLER: ['wallet.view'],
  HOST: ['room.create', 'room.update'],
  USER: ['room.create'],
};
