/**
 * Video-room runtime enums — transient connection/session/stream state that
 * lives in Redis + socket payloads, NOT in Postgres. Durable, DB-backed
 * vocabulary (VideoRoomStatus / VideoRoomVisibility / VideoRoomMemberRole /
 * VideoRoomLogAction) is generated by Prisma from `video_rooms.prisma` and
 * imported from `@prisma/client`. Keep these two families distinct: persisted
 * state is a Prisma enum; ephemeral state is one of the enums below.
 */

/** A viewer/participant socket's live connection lifecycle. */
export enum ConnectionStatus {
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  RECONNECTING = 'RECONNECTING',
  DISCONNECTED = 'DISCONNECTED',
}

/** Whether a connection may publish media (on a seat) or only subscribe (audience). */
export enum ConnectionType {
  PUBLISHER = 'PUBLISHER',
  SUBSCRIBER = 'SUBSCRIBER',
}

/** A registered session's lifecycle in the session registry. */
export enum SessionStatus {
  ACTIVE = 'ACTIVE',
  IDLE = 'IDLE',
  EXPIRED = 'EXPIRED',
  ENDED = 'ENDED',
}

/**
 * A member's live presence in a room (VR-3). The single, client-facing presence
 * vocabulary reported by GET /presence + the `presence_updated` socket event.
 * Derived from a session's heartbeat freshness + the client `inBackground` flag
 * by the pure `derivePresenceState` helper — never hand-set outside it (except
 * the sticky terminals LEFT and the observed DISCONNECTED, which it respects).
 *
 * ONLINE      — heartbeating, foreground.
 * CONNECTING  — session registered, first heartbeat not yet confirmed.
 * IDLE        — heartbeating but backgrounded (or inactive past idleTimeout).
 * RECONNECTING— heartbeats late, still inside the reconnect grace window.
 * DISCONNECTED— socket confirmed dead (infra presence event), still within grace.
 * LEFT        — explicit leave, or grace elapsed (monitor reclaim). Terminal.
 * OFFLINE     — no session at all.
 */
export enum VideoRoomPresenceState {
  CONNECTING = 'CONNECTING',
  ONLINE = 'ONLINE',
  IDLE = 'IDLE',
  RECONNECTING = 'RECONNECTING',
  DISCONNECTED = 'DISCONNECTED',
  LEFT = 'LEFT',
  OFFLINE = 'OFFLINE',
}

/** A seat holder's live status (multi-seat video, later phases). */
export enum ParticipantStatus {
  ACTIVE = 'ACTIVE',
  MUTED = 'MUTED',
  AWAY = 'AWAY',
}

/**
 * The viewer-facing presence vocabulary (VR-6). A pure projection of the
 * VideoRoomPresenceState FSM — see services/video-room-viewer-presence.projection.ts.
 * WATCHING = live+foreground, BACKGROUND = backgrounded, others pass through.
 */
export enum ViewerStatus {
  WATCHING = 'WATCHING',
  BACKGROUND = 'BACKGROUND',
  ONLINE = 'ONLINE',
  RECONNECTING = 'RECONNECTING',
  LEFT = 'LEFT',
  OFFLINE = 'OFFLINE',
}

/** A seat's video stream state (later phases). */
export enum StreamStatus {
  IDLE = 'IDLE',
  PUBLISHING = 'PUBLISHING',
  PAUSED = 'PAUSED',
  STOPPED = 'STOPPED',
}

/**
 * The media (RTC) provider backing a room. ZEGO is the live provider; the enum
 * exists so the IMediaProvider seam can advertise which backend issued a token
 * and so a future provider is a new value, not a code change.
 */
export enum MediaProviderKind {
  ZEGO = 'ZEGO',
  AGORA = 'AGORA',
}

/** The media stream FSM (VR-5). Ephemeral — Redis + socket only, never Postgres. */
export enum MediaStreamState {
  CREATED = 'CREATED',
  CONNECTING = 'CONNECTING',
  LIVE = 'LIVE',
  PAUSED = 'PAUSED',
  STOPPED = 'STOPPED',
  FAILED = 'FAILED',
  RECOVERING = 'RECOVERING',
  ENDED = 'ENDED',
}
/** What a publish stream carries. SCREEN is shape-ready (VR-5 implements CAMERA only). */
export enum MediaStreamKind {
  CAMERA = 'CAMERA',
  SCREEN = 'SCREEN',
}
/** Client-detected audio output route (synchronized + broadcast server-side). */
export enum AudioOutput {
  SPEAKER = 'SPEAKER',
  EARPIECE = 'EARPIECE',
  BLUETOOTH = 'BLUETOOTH',
  WIRED = 'WIRED',
}
/** Configurable video quality tiers; ADAPTIVE defers to the network-driven selector. */
export enum VideoQualityProfile {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  HD = 'HD',
  FULL_HD = 'FULL_HD',
  ADAPTIVE = 'ADAPTIVE',
}
/** Which camera a publisher is using. */
export enum CameraFacing {
  FRONT = 'FRONT',
  REAR = 'REAR',
}
