/**
 * Stable, machine-readable error codes returned in the error envelope so
 * clients can branch on failures without parsing messages. Extend per domain.
 */
export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL: 'INTERNAL',

  // ---- Auth domain ----
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  OTP_BLOCKED: 'OTP_BLOCKED',
  OTP_RESEND_LIMIT: 'OTP_RESEND_LIMIT',
  OTP_COOLDOWN: 'OTP_COOLDOWN',
  DUPLICATE_MOBILE: 'DUPLICATE_MOBILE',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  DUPLICATE_USERNAME: 'DUPLICATE_USERNAME',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  ACCOUNT_BANNED: 'ACCOUNT_BANNED',
  UNDERAGE: 'UNDERAGE',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_HIJACK_DETECTED: 'SESSION_HIJACK_DETECTED',
  SESSION_LIMIT: 'SESSION_LIMIT',
  GUEST_FORBIDDEN: 'GUEST_FORBIDDEN',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVALID_SOCIAL_TOKEN: 'INVALID_SOCIAL_TOKEN',

  // ---- User / profile domain ----
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  USERNAME_INVALID: 'USERNAME_INVALID',
  VERIFICATION_PENDING: 'VERIFICATION_PENDING',
  VERIFICATION_NOT_FOUND: 'VERIFICATION_NOT_FOUND',

  // ---- Device domain ----
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DEVICE_FORBIDDEN: 'DEVICE_FORBIDDEN',
  DEVICE_CHANGE_PENDING: 'DEVICE_CHANGE_PENDING',
  STAFF_IP_NOT_ALLOWED: 'STAFF_IP_NOT_ALLOWED',

  // ---- Privacy / Safety domain ----
  CANNOT_BLOCK_SELF: 'CANNOT_BLOCK_SELF',
  ALREADY_BLOCKED: 'ALREADY_BLOCKED',
  USER_BLOCKED: 'USER_BLOCKED',
  PRIVACY_RESTRICTED: 'PRIVACY_RESTRICTED',

  // ---- Audio Room domain ----
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_LIMIT_REACHED: 'ROOM_LIMIT_REACHED',
  ROOM_LOCKED: 'ROOM_LOCKED',
  ROOM_PASSWORD_INVALID: 'ROOM_PASSWORD_INVALID',
  ROOM_FULL: 'ROOM_FULL',
  ROOM_ENDED: 'ROOM_ENDED',
  NOT_ROOM_OWNER: 'NOT_ROOM_OWNER',
  NOT_ROOM_MEMBER: 'NOT_ROOM_MEMBER',
  ROOM_CATEGORY_INVALID: 'ROOM_CATEGORY_INVALID',
  ROOM_LANGUAGE_INVALID: 'ROOM_LANGUAGE_INVALID',

  // ---- Audio Room seats / roles (AR-1) ----
  NOT_ROOM_ADMIN: 'NOT_ROOM_ADMIN',
  SEAT_NOT_FOUND: 'SEAT_NOT_FOUND',
  SEAT_TAKEN: 'SEAT_TAKEN',
  SEAT_LOCKED: 'SEAT_LOCKED',
  SEAT_FULL: 'SEAT_FULL',
  ALREADY_ON_SEAT: 'ALREADY_ON_SEAT',
  NOT_ON_SEAT: 'NOT_ON_SEAT',
  SEAT_TYPE_FORBIDDEN: 'SEAT_TYPE_FORBIDDEN',
  SEAT_LAYOUT_INVALID: 'SEAT_LAYOUT_INVALID',
  SEAT_REQUEST_NOT_FOUND: 'SEAT_REQUEST_NOT_FOUND',
  SEAT_REQUEST_EXISTS: 'SEAT_REQUEST_EXISTS',
  SEAT_INVITATION_NOT_FOUND: 'SEAT_INVITATION_NOT_FOUND',
  SEAT_INVITATION_EXPIRED: 'SEAT_INVITATION_EXPIRED',
  SEAT_RESERVED: 'SEAT_RESERVED',
  SEAT_REQUEST_EXPIRED: 'SEAT_REQUEST_EXPIRED',
  /** VR-8 — a seat-request status transition that the state machine forbids. */
  SEAT_REQUEST_INVALID_TRANSITION: 'SEAT_REQUEST_INVALID_TRANSITION',
  /** VR-8 — an invitation status transition that the state machine forbids. */
  SEAT_INVITATION_INVALID_TRANSITION: 'SEAT_INVITATION_INVALID_TRANSITION',
  /** VR-8 — retry refused: attemptCount has reached the configured maximum. */
  SEAT_RETRY_EXHAUSTED: 'SEAT_RETRY_EXHAUSTED',
  SEAT_SWITCH_INVALID: 'SEAT_SWITCH_INVALID',
  SEAT_TRANSFER_INVALID: 'SEAT_TRANSFER_INVALID',
  DUPLICATE_SEAT_INVITATION: 'DUPLICATE_SEAT_INVITATION',
  DUPLICATE_SEAT_REQUEST: 'DUPLICATE_SEAT_REQUEST',
  QUEUE_ENTRY_NOT_FOUND: 'QUEUE_ENTRY_NOT_FOUND',
  ROLE_INVALID: 'ROLE_INVALID',
  ADMIN_LIMIT_REACHED: 'ADMIN_LIMIT_REACHED',

  // ---- Audio Room voice (AR-2) ----
  VOICE_NOT_CONFIGURED: 'VOICE_NOT_CONFIGURED',
  VOICE_SESSION_NOT_FOUND: 'VOICE_SESSION_NOT_FOUND',
  VOICE_NOT_IN_CHANNEL: 'VOICE_NOT_IN_CHANNEL',
  NOT_ALLOWED_TO_PUBLISH: 'NOT_ALLOWED_TO_PUBLISH',

  // ---- Audio Room moderation (AR-3) ----
  ROOM_KICKED: 'ROOM_KICKED',
  ALREADY_KICKED: 'ALREADY_KICKED',
  KICK_NOT_FOUND: 'KICK_NOT_FOUND',
  ROOM_BANNED: 'ROOM_BANNED',
  ALREADY_BANNED: 'ALREADY_BANNED',
  BAN_NOT_FOUND: 'BAN_NOT_FOUND',
  PLATFORM_BANNED: 'PLATFORM_BANNED',
  MEMBER_MUTED: 'MEMBER_MUTED',
  ALREADY_MUTED: 'ALREADY_MUTED',
  MUTE_NOT_FOUND: 'MUTE_NOT_FOUND',
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  DUPLICATE_REPORT: 'DUPLICATE_REPORT',
  CANNOT_MODERATE_OWNER: 'CANNOT_MODERATE_OWNER',
  CANNOT_MODERATE_SELF: 'CANNOT_MODERATE_SELF',
  INSUFFICIENT_AUTHORITY: 'INSUFFICIENT_AUTHORITY',
  APPEAL_EXISTS: 'APPEAL_EXISTS',
  APPEAL_NOT_FOUND: 'APPEAL_NOT_FOUND',

  // ---- Audio Room chat (AR-4) ----
  CHAT_DISABLED: 'CHAT_DISABLED',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
  CHAT_RATE_LIMITED: 'CHAT_RATE_LIMITED',
  CHAT_SLOW_MODE: 'CHAT_SLOW_MODE',
  DUPLICATE_MESSAGE: 'DUPLICATE_MESSAGE',
  BLOCKED_WORD: 'BLOCKED_WORD',
  ALREADY_PINNED: 'ALREADY_PINNED',
  PIN_NOT_FOUND: 'PIN_NOT_FOUND',
  CHAT_REPORT_NOT_FOUND: 'CHAT_REPORT_NOT_FOUND',
  BLOCKED_WORD_NOT_FOUND: 'BLOCKED_WORD_NOT_FOUND',
  INVALID_REGEX: 'INVALID_REGEX',

  // ---- Video Room chat (VR-9) ----
  VIDEO_ROOM_CHAT_MODE_RESTRICTED: 'VIDEO_ROOM_CHAT_MODE_RESTRICTED',
  VIDEO_ROOM_MESSAGE_EDIT_WINDOW_EXPIRED: 'VIDEO_ROOM_MESSAGE_EDIT_WINDOW_EXPIRED',
  VIDEO_ROOM_MESSAGE_RECALL_WINDOW_EXPIRED: 'VIDEO_ROOM_MESSAGE_RECALL_WINDOW_EXPIRED',
  VIDEO_ROOM_MESSAGE_NOT_EDITABLE: 'VIDEO_ROOM_MESSAGE_NOT_EDITABLE',
  VIDEO_ROOM_REPLY_TARGET_INVALID: 'VIDEO_ROOM_REPLY_TARGET_INVALID',
  VIDEO_ROOM_ANNOUNCEMENT_NOT_FOUND: 'VIDEO_ROOM_ANNOUNCEMENT_NOT_FOUND',
  VIDEO_ROOM_ATTACHMENT_LIMIT: 'VIDEO_ROOM_ATTACHMENT_LIMIT',

  // ---- Video Room domain (VR-0) ----
  VIDEO_ROOM_NOT_FOUND: 'VIDEO_ROOM_NOT_FOUND',
  VIDEO_ROOM_ALREADY_EXISTS: 'VIDEO_ROOM_ALREADY_EXISTS',
  VIDEO_ROOM_UNAVAILABLE: 'VIDEO_ROOM_UNAVAILABLE',
  VIDEO_ROOM_CAPACITY_EXCEEDED: 'VIDEO_ROOM_CAPACITY_EXCEEDED',
  VIDEO_ROOM_HOST_UNAVAILABLE: 'VIDEO_ROOM_HOST_UNAVAILABLE',
  VIDEO_ROOM_INVALID_STATE: 'VIDEO_ROOM_INVALID_STATE',
  VIDEO_ROOM_SESSION_EXPIRED: 'VIDEO_ROOM_SESSION_EXPIRED',
  VIDEO_ROOM_MEDIA_NOT_CONFIGURED: 'VIDEO_ROOM_MEDIA_NOT_CONFIGURED',
  VIDEO_ROOM_CONFIG_INVALID: 'VIDEO_ROOM_CONFIG_INVALID',
  // ---- Video Room lifecycle (VR-2) ----
  VIDEO_ROOM_FORBIDDEN: 'VIDEO_ROOM_FORBIDDEN',
  /** Settings row absent for an existing room — data-integrity fault (500). */
  VIDEO_ROOM_SETTINGS_MISSING: 'VIDEO_ROOM_SETTINGS_MISSING',
  VIDEO_ROOM_DELETED: 'VIDEO_ROOM_DELETED',
  VIDEO_ROOM_ALREADY_LOCKED: 'VIDEO_ROOM_ALREADY_LOCKED',
  // ---- Video Room member lifecycle (VR-3) ----
  /** Join attempted on a room whose status is not LIVE (409). */
  VIDEO_ROOM_ENDED: 'VIDEO_ROOM_ENDED',
  /** Room password missing/incorrect on a locked room (400). */
  VIDEO_ROOM_PASSWORD_INVALID: 'VIDEO_ROOM_PASSWORD_INVALID',
  /** User is on the room's block-list (403). */
  VIDEO_ROOM_BLOCKED: 'VIDEO_ROOM_BLOCKED',
  /** Action requires an active membership the caller does not have (403). */
  VIDEO_ROOM_NOT_MEMBER: 'VIDEO_ROOM_NOT_MEMBER',
  /** A second live session for the same (user, device) was detected (409). */
  VIDEO_ROOM_DUPLICATE_SESSION: 'VIDEO_ROOM_DUPLICATE_SESSION',
  /** Reconnect failed — the session was already reclaimed or the room is gone (409). */
  VIDEO_ROOM_RECONNECT_FAILED: 'VIDEO_ROOM_RECONNECT_FAILED',
  VIDEO_ROOM_PROMOTION_FAILED: 'VIDEO_ROOM_PROMOTION_FAILED',
  VIDEO_ROOM_DEMOTION_FAILED: 'VIDEO_ROOM_DEMOTION_FAILED',
  VIDEO_ROOM_NOT_VIEWER: 'VIDEO_ROOM_NOT_VIEWER',
  VIDEO_ROOM_NOT_PARTICIPANT: 'VIDEO_ROOM_NOT_PARTICIPANT',

  // ---- Video Room media (VR-5) ----
  VIDEO_ROOM_STREAM_INVALID_STATE: 'VIDEO_ROOM_STREAM_INVALID_STATE',
  VIDEO_ROOM_DUPLICATE_STREAM: 'VIDEO_ROOM_DUPLICATE_STREAM',
  VIDEO_ROOM_MEDIA_SESSION_INVALID: 'VIDEO_ROOM_MEDIA_SESSION_INVALID',
  VIDEO_ROOM_STREAM_PUBLISH_FAILED: 'VIDEO_ROOM_STREAM_PUBLISH_FAILED',
  VIDEO_ROOM_STREAM_SUBSCRIBE_FAILED: 'VIDEO_ROOM_STREAM_SUBSCRIBE_FAILED',
  VIDEO_ROOM_CAMERA_ERROR: 'VIDEO_ROOM_CAMERA_ERROR',
  VIDEO_ROOM_MICROPHONE_ERROR: 'VIDEO_ROOM_MICROPHONE_ERROR',
  VIDEO_ROOM_MEDIA_SEAT_REQUIRED: 'VIDEO_ROOM_MEDIA_SEAT_REQUIRED',
  VIDEO_ROOM_MEDIA_RECOVERY_FAILED: 'VIDEO_ROOM_MEDIA_RECOVERY_FAILED',
  VIDEO_ROOM_SUBSCRIPTION_LIMIT: 'VIDEO_ROOM_SUBSCRIPTION_LIMIT',

  // ---- Video Room roles & permissions (VR-7) ----
  VIDEO_ROOM_ROLE_NOT_FOUND: 'VIDEO_ROOM_ROLE_NOT_FOUND',
  VIDEO_ROOM_ROLE_INVALID: 'VIDEO_ROOM_ROLE_INVALID',
  VIDEO_ROOM_ROLE_LIMIT_EXCEEDED: 'VIDEO_ROOM_ROLE_LIMIT_EXCEEDED',
  VIDEO_ROOM_DUPLICATE_ROLE: 'VIDEO_ROOM_DUPLICATE_ROLE',
  VIDEO_ROOM_INVALID_HIERARCHY: 'VIDEO_ROOM_INVALID_HIERARCHY',
  VIDEO_ROOM_CANNOT_MODERATE_OWNER: 'VIDEO_ROOM_CANNOT_MODERATE_OWNER',
  VIDEO_ROOM_OWNERSHIP_TRANSFER_FAILED: 'VIDEO_ROOM_OWNERSHIP_TRANSFER_FAILED',

  // ---- Direct messaging (chat module) ----
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  NOT_A_PARTICIPANT: 'NOT_A_PARTICIPANT',
  CANNOT_MESSAGE_SELF: 'CANNOT_MESSAGE_SELF',
  /** The recipient's privacy level (messagePermission) forbids this sender. */
  MESSAGING_NOT_ALLOWED: 'MESSAGING_NOT_ALLOWED',
  /** The conversation is still a pending request — the recipient must accept first. */
  CHAT_REQUEST_PENDING: 'CHAT_REQUEST_PENDING',
  CHAT_REQUEST_NOT_FOUND: 'CHAT_REQUEST_NOT_FOUND',
  DM_NOT_FOUND: 'DM_NOT_FOUND',
  DM_TOO_LONG: 'DM_TOO_LONG',
  DM_RATE_LIMITED: 'DM_RATE_LIMITED',
  DM_NOT_EDITABLE: 'DM_NOT_EDITABLE',
  ATTACHMENT_INVALID: 'ATTACHMENT_INVALID',
  TOO_MANY_ATTACHMENTS: 'TOO_MANY_ATTACHMENTS',
  REACTION_NOT_FOUND: 'REACTION_NOT_FOUND',
  /** The user already has the maximum number of pinned conversations. */
  PIN_LIMIT_REACHED: 'PIN_LIMIT_REACHED',
  /** The message's edit window has closed, or it is not the sender's to edit. */
  DM_EDIT_WINDOW_CLOSED: 'DM_EDIT_WINDOW_CLOSED',
  /** A rich message (GIFT/ROOM_INVITE/...) is missing the metadata its type requires. */
  METADATA_INVALID: 'METADATA_INVALID',
  CANNOT_REPORT_SELF: 'CANNOT_REPORT_SELF',
  /** The user has starred as many messages as they are allowed to. */
  STAR_LIMIT_REACHED: 'STAR_LIMIT_REACHED',
  /**
   * The message cannot be pinned to the thread: it belongs to another
   * conversation, is deleted, or the pinner has hidden it for themselves.
   */
  PIN_MESSAGE_INVALID: 'PIN_MESSAGE_INVALID',

  // ---- Private calls (1:1 voice / video) ----
  CALL_NOT_FOUND: 'CALL_NOT_FOUND',
  /** The callee's privacy settings do not permit a call from this user. */
  CALL_NOT_ALLOWED: 'CALL_NOT_ALLOWED',
  /** One of the two users has blocked the other. */
  CALL_BLOCKED: 'CALL_BLOCKED',
  /** The callee is already in another call. */
  CALL_BUSY: 'CALL_BUSY',
  /** The caller is already in a call and must end it before placing another. */
  CALL_ALREADY_ACTIVE: 'CALL_ALREADY_ACTIVE',
  /** The transition is not legal from the call's current status (e.g. accepting an ended call). */
  CALL_INVALID_STATE: 'CALL_INVALID_STATE',
  /** The requesting user is neither the caller nor the callee. */
  CALL_NOT_PARTICIPANT: 'CALL_NOT_PARTICIPANT',
  CANNOT_CALL_SELF: 'CANNOT_CALL_SELF',
  CALL_RATE_LIMITED: 'CALL_RATE_LIMITED',

  // ---- Wallet (economy) ----
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  UNSUPPORTED_CURRENCY: 'UNSUPPORTED_CURRENCY',
  WALLET_TXN_NOT_FOUND: 'WALLET_TXN_NOT_FOUND',
  WALLET_NOT_ACTIVE: 'WALLET_NOT_ACTIVE',

  // ---- Gifts (AR-5) ----
  GIFT_NOT_FOUND: 'GIFT_NOT_FOUND',
  GIFT_DISABLED: 'GIFT_DISABLED',
  GIFT_INVALID_QUANTITY: 'GIFT_INVALID_QUANTITY',
  GIFT_VIP_RESTRICTED: 'GIFT_VIP_RESTRICTED',
  // No CANNOT_GIFT_SELF: self-gifting is a supported product flow. A user may
  // name themselves as the recipient of any gift, in audio and video rooms alike.
  GIFT_RECEIVER_INVALID: 'GIFT_RECEIVER_INVALID',
  GIFT_CONTEXT_INVALID: 'GIFT_CONTEXT_INVALID',
  GIFT_RATE_LIMITED: 'GIFT_RATE_LIMITED',
  // ---- VR-10 (video-room gift engine) ----
  GIFT_TOO_MANY_RECEIVERS: 'GIFT_TOO_MANY_RECEIVERS',
  GIFT_QUEUE_ERROR: 'GIFT_QUEUE_ERROR',
  GIFT_DELIVERY_FAILED: 'GIFT_DELIVERY_FAILED',
  GIFT_COMBO_ERROR: 'GIFT_COMBO_ERROR',
  WALLET_TRANSACTION_FAILED: 'WALLET_TRANSACTION_FAILED',
  VIDEO_ROOM_GIFTS_DISABLED: 'VIDEO_ROOM_GIFTS_DISABLED',
  GIFT_COUNTRY_RESTRICTED: 'GIFT_COUNTRY_RESTRICTED',
  GIFT_ALREADY_REVERSED: 'GIFT_ALREADY_REVERSED',
  GIFT_TRANSACTION_NOT_FOUND: 'GIFT_TRANSACTION_NOT_FOUND',
  DUPLICATE_GIFT: 'DUPLICATE_GIFT',

  // ---- Backpack ----
  BACKPACK_ITEM_NOT_FOUND: 'BACKPACK_ITEM_NOT_FOUND',
  BACKPACK_ITEM_NOT_EQUIPPABLE: 'BACKPACK_ITEM_NOT_EQUIPPABLE',
  BACKPACK_ITEM_NOT_TRANSFERABLE: 'BACKPACK_ITEM_NOT_TRANSFERABLE',
  BACKPACK_ITEM_EXPIRED: 'BACKPACK_ITEM_EXPIRED',
  CANNOT_TRANSFER_SELF: 'CANNOT_TRANSFER_SELF',

  // ---- Treasure boxes & rocket events (AR-6) ----
  TREASURE_CONFIG_INCOMPLETE: 'TREASURE_CONFIG_INCOMPLETE',
  TREASURE_SESSION_EXISTS: 'TREASURE_SESSION_EXISTS',
  TREASURE_SESSION_NOT_FOUND: 'TREASURE_SESSION_NOT_FOUND',
  TREASURE_NOT_AUTHORIZED: 'TREASURE_NOT_AUTHORIZED',
  TREASURE_CONFIG_NOT_FOUND: 'TREASURE_CONFIG_NOT_FOUND',

  // ---- VR-11 video room treasure engine ----
  VIDEO_ROOM_TREASURE_INVALID: 'VIDEO_ROOM_TREASURE_INVALID',
  VIDEO_ROOM_TREASURE_PROGRESS_FAILED: 'VIDEO_ROOM_TREASURE_PROGRESS_FAILED',
  VIDEO_ROOM_TREASURE_UNLOCK_FAILED: 'VIDEO_ROOM_TREASURE_UNLOCK_FAILED',
  VIDEO_ROOM_TREASURE_POOL_INVALID: 'VIDEO_ROOM_TREASURE_POOL_INVALID',
  VIDEO_ROOM_TREASURE_WINNER_SELECTION_FAILED: 'VIDEO_ROOM_TREASURE_WINNER_SELECTION_FAILED',
  VIDEO_ROOM_TREASURE_DISTRIBUTION_FAILED: 'VIDEO_ROOM_TREASURE_DISTRIBUTION_FAILED',
  VIDEO_ROOM_TREASURE_DUPLICATE_REWARD: 'VIDEO_ROOM_TREASURE_DUPLICATE_REWARD',
  VIDEO_ROOM_TREASURE_NOT_FOUND: 'VIDEO_ROOM_TREASURE_NOT_FOUND',
  VIDEO_ROOM_TREASURE_ALREADY_ACTIVE: 'VIDEO_ROOM_TREASURE_ALREADY_ACTIVE',
  VIDEO_ROOM_TREASURE_DISABLED: 'VIDEO_ROOM_TREASURE_DISABLED',
  VIDEO_ROOM_TREASURE_NOT_AUTHORIZED: 'VIDEO_ROOM_TREASURE_NOT_AUTHORIZED',

  // ---- VR-12 video room PK battle engine ----
  VIDEO_ROOM_PK_INVALID: 'VIDEO_ROOM_PK_INVALID',
  VIDEO_ROOM_PK_NOT_FOUND: 'VIDEO_ROOM_PK_NOT_FOUND',
  VIDEO_ROOM_PK_ALREADY_ACTIVE: 'VIDEO_ROOM_PK_ALREADY_ACTIVE',
  VIDEO_ROOM_PK_INVITATION_FAILED: 'VIDEO_ROOM_PK_INVITATION_FAILED',
  VIDEO_ROOM_PK_SCORE_FAILED: 'VIDEO_ROOM_PK_SCORE_FAILED',
  VIDEO_ROOM_PK_REWARD_FAILED: 'VIDEO_ROOM_PK_REWARD_FAILED',
  VIDEO_ROOM_PK_WINNER_FAILED: 'VIDEO_ROOM_PK_WINNER_FAILED',
  VIDEO_ROOM_PK_COUNTDOWN_FAILED: 'VIDEO_ROOM_PK_COUNTDOWN_FAILED',
  VIDEO_ROOM_PK_RECOVERY_FAILED: 'VIDEO_ROOM_PK_RECOVERY_FAILED',
  VIDEO_ROOM_PK_DISABLED: 'VIDEO_ROOM_PK_DISABLED',
  VIDEO_ROOM_PK_NOT_AUTHORIZED: 'VIDEO_ROOM_PK_NOT_AUTHORIZED',

  // ---- VR-13 video room ranking & leaderboard engine ----
  VIDEO_ROOM_RANKING_INVALID: 'VIDEO_ROOM_RANKING_INVALID',
  VIDEO_ROOM_LEADERBOARD_INVALID: 'VIDEO_ROOM_LEADERBOARD_INVALID',
  VIDEO_ROOM_RANKING_AGGREGATION_FAILED: 'VIDEO_ROOM_RANKING_AGGREGATION_FAILED',
  VIDEO_ROOM_RANKING_CACHE_FAILED: 'VIDEO_ROOM_RANKING_CACHE_FAILED',
  VIDEO_ROOM_RANKING_PERIOD_INVALID: 'VIDEO_ROOM_RANKING_PERIOD_INVALID',
  ROCKET_CONFIG_NOT_FOUND: 'ROCKET_CONFIG_NOT_FOUND',

  // ---- Video Room moderation & safety engine (Phase 16) ----
  VIDEO_ROOM_ALREADY_BLOCKED: 'VIDEO_ROOM_ALREADY_BLOCKED',
  VIDEO_ROOM_BLOCK_NOT_FOUND: 'VIDEO_ROOM_BLOCK_NOT_FOUND',
  VIDEO_ROOM_ALREADY_MUTED: 'VIDEO_ROOM_ALREADY_MUTED',
  VIDEO_ROOM_MUTE_NOT_FOUND: 'VIDEO_ROOM_MUTE_NOT_FOUND',
  VIDEO_ROOM_CANNOT_MODERATE_SELF: 'VIDEO_ROOM_CANNOT_MODERATE_SELF',
  VIDEO_ROOM_DUPLICATE_REPORT: 'VIDEO_ROOM_DUPLICATE_REPORT',
  VIDEO_ROOM_REPORT_NOT_FOUND: 'VIDEO_ROOM_REPORT_NOT_FOUND',
  VIDEO_ROOM_REPORT_NOT_PENDING: 'VIDEO_ROOM_REPORT_NOT_PENDING',

  // ---- Cosmetics / EXP / Levels / VIP (AR-7) ----
  COSMETIC_NOT_FOUND: 'COSMETIC_NOT_FOUND',
  LEVEL_CONFIG_NOT_FOUND: 'LEVEL_CONFIG_NOT_FOUND',
  VIP_CONFIG_NOT_FOUND: 'VIP_CONFIG_NOT_FOUND',

  // ---- Events / Room appearance (AR-8) ----
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  EVENT_NOT_ACTIVE: 'EVENT_NOT_ACTIVE',
  EVENT_ALREADY_CLAIMED: 'EVENT_ALREADY_CLAIMED',
  EVENT_NOT_ELIGIBLE: 'EVENT_NOT_ELIGIBLE',
  EVENT_NOT_CLAIMABLE: 'EVENT_NOT_CLAIMABLE',
  EVENT_INVALID_WINDOW: 'EVENT_INVALID_WINDOW',
  COSMETIC_NOT_OWNED: 'COSMETIC_NOT_OWNED',
  COSMETIC_WRONG_TYPE: 'COSMETIC_WRONG_TYPE',
  APPEARANCE_NOT_AUTHORIZED: 'APPEARANCE_NOT_AUTHORIZED',

  // ---- Premium features (AR-9) ----
  COSMETIC_NOT_PURCHASABLE: 'COSMETIC_NOT_PURCHASABLE',
  PREMIUM_SEAT_UNAVAILABLE: 'PREMIUM_SEAT_UNAVAILABLE',
  PREMIUM_SEAT_ALREADY_HELD: 'PREMIUM_SEAT_ALREADY_HELD',
  ALREADY_ELEVATED: 'ALREADY_ELEVATED',
  PREMIUM_SEAT_NOT_FOUND: 'PREMIUM_SEAT_NOT_FOUND',
  WATCH_PARTY_NOT_AUTHORIZED: 'WATCH_PARTY_NOT_AUTHORIZED',
  WATCH_PARTY_INACTIVE: 'WATCH_PARTY_INACTIVE',
  INVALID_VIDEO_ID: 'INVALID_VIDEO_ID',

  // ---- PK Battles (AR-10) ----
  PK_NOT_AUTHORIZED: 'PK_NOT_AUTHORIZED',
  PK_ALREADY_ACTIVE: 'PK_ALREADY_ACTIVE',
  PK_NOT_FOUND: 'PK_NOT_FOUND',
  PK_INVALID_PARTICIPANTS: 'PK_INVALID_PARTICIPANTS',
  PK_PARTICIPANT_NOT_MEMBER: 'PK_PARTICIPANT_NOT_MEMBER',

  // ---- Analytics & Reporting (AR-13) ----
  ANALYTICS_NOT_AUTHORIZED: 'ANALYTICS_NOT_AUTHORIZED',

  // ---- Games (AR-11) ----
  GAME_NOT_FOUND: 'GAME_NOT_FOUND',
  GAME_DISABLED: 'GAME_DISABLED',
  GAME_INVALID_STAKE: 'GAME_INVALID_STAKE',
  GAME_LOBBY_NOT_FOUND: 'GAME_LOBBY_NOT_FOUND',
  GAME_LOBBY_NOT_OPEN: 'GAME_LOBBY_NOT_OPEN',
  GAME_LOBBY_FULL: 'GAME_LOBBY_FULL',
  GAME_ALREADY_IN_LOBBY: 'GAME_ALREADY_IN_LOBBY',
  GAME_NOT_IN_LOBBY: 'GAME_NOT_IN_LOBBY',
  GAME_NOT_HOST: 'GAME_NOT_HOST',
  GAME_INSUFFICIENT_PLAYERS: 'GAME_INSUFFICIENT_PLAYERS',
  GAME_SESSION_NOT_FOUND: 'GAME_SESSION_NOT_FOUND',
  GAME_SESSION_NOT_ACTIVE: 'GAME_SESSION_NOT_ACTIVE',
  GAME_ALREADY_SETTLED: 'GAME_ALREADY_SETTLED',
  GAME_INVALID_PAYOUT: 'GAME_INVALID_PAYOUT',
  GAME_PAYOUT_EXCEEDS_POT: 'GAME_PAYOUT_EXCEEDS_POT',
  GAME_INVALID_PARTICIPANT: 'GAME_INVALID_PARTICIPANT',
  GAME_NOT_PARTICIPANT: 'GAME_NOT_PARTICIPANT',
  GAME_NOT_AUTHORIZED: 'GAME_NOT_AUTHORIZED',
  GAME_NOT_YOUR_TURN: 'GAME_NOT_YOUR_TURN',
  GAME_ALREADY_OVER: 'GAME_ALREADY_OVER',
  GAME_RESULT_PENDING_CONFIRMATION: 'GAME_RESULT_PENDING_CONFIRMATION',
  GAME_RESULT_ALREADY_REPORTED: 'GAME_RESULT_ALREADY_REPORTED',
  GAME_RESULT_DISPUTED: 'GAME_RESULT_DISPUTED',
  GAME_HAS_MOVES: 'GAME_HAS_MOVES',
  // Matchmaking + 2v2 teams (Phase 3)
  GAME_ALREADY_QUEUED: 'GAME_ALREADY_QUEUED',
  GAME_NOT_QUEUED: 'GAME_NOT_QUEUED',
  GAME_MATCH_NOT_FOUND: 'GAME_MATCH_NOT_FOUND',
  GAME_MATCH_EXPIRED: 'GAME_MATCH_EXPIRED',
  GAME_2V2_UNSUPPORTED: 'GAME_2V2_UNSUPPORTED',
  GAME_TEAM_FULL: 'GAME_TEAM_FULL',
  GAME_TEAM_UNBALANCED: 'GAME_TEAM_UNBALANCED',
  GAME_NOT_TEAM_MODE: 'GAME_NOT_TEAM_MODE',
  GAME_MATCHMAKING_DISABLED: 'GAME_MATCHMAKING_DISABLED',
  GAME_LOBBY_BAD_PASSWORD: 'GAME_LOBBY_BAD_PASSWORD',
  GAME_NOT_LOBBY_MEMBER: 'GAME_NOT_LOBBY_MEMBER',
  // Audio-room integration
  GAME_ROOM_ALREADY_ACTIVE: 'GAME_ROOM_ALREADY_ACTIVE',
  /** A casino bet placed through the room-window path failed validation/balance. */
  CASINO_BET_INVALID: 'CASINO_BET_INVALID',

  // ---- Lucky Packets (AR-14) ----
  LUCKY_PACKET_NOT_AUTHORIZED: 'LUCKY_PACKET_NOT_AUTHORIZED',
  LUCKY_PACKET_INVALID_PARAMS: 'LUCKY_PACKET_INVALID_PARAMS',
  LUCKY_PACKET_NOT_FOUND: 'LUCKY_PACKET_NOT_FOUND',
  LUCKY_PACKET_EXPIRED: 'LUCKY_PACKET_EXPIRED',
  LUCKY_PACKET_EXHAUSTED: 'LUCKY_PACKET_EXHAUSTED',
  LUCKY_PACKET_ALREADY_CLAIMED: 'LUCKY_PACKET_ALREADY_CLAIMED',

  // ---- Room Interactive Utilities (AR-15) ----
  ROOM_UTIL_NOT_AUTHORIZED: 'ROOM_UTIL_NOT_AUTHORIZED',
  POLL_NOT_FOUND: 'POLL_NOT_FOUND',
  POLL_ENDED: 'POLL_ENDED',
  POLL_ALREADY_VOTED: 'POLL_ALREADY_VOTED',
  POLL_OPTION_INVALID: 'POLL_OPTION_INVALID',
  RANDOM_PICK_INVALID_RANGE: 'RANDOM_PICK_INVALID_RANGE',
  RANDOM_PICK_NO_CANDIDATES: 'RANDOM_PICK_NO_CANDIDATES',
  SPIN_WHEEL_NOT_FOUND: 'SPIN_WHEEL_NOT_FOUND',
  COUNTDOWN_EXISTS: 'COUNTDOWN_EXISTS',
  COUNTDOWN_NOT_FOUND: 'COUNTDOWN_NOT_FOUND',
  COUNTDOWN_NOT_RUNNING: 'COUNTDOWN_NOT_RUNNING',
  COUNTDOWN_NOT_PAUSED: 'COUNTDOWN_NOT_PAUSED',

  // ---- Social graph (friends / follow / invitations) ----
  CANNOT_FRIEND_SELF: 'CANNOT_FRIEND_SELF',
  ALREADY_FRIENDS: 'ALREADY_FRIENDS',
  NOT_FRIENDS: 'NOT_FRIENDS',
  FRIEND_REQUEST_NOT_FOUND: 'FRIEND_REQUEST_NOT_FOUND',
  FRIEND_REQUEST_EXISTS: 'FRIEND_REQUEST_EXISTS',
  FRIEND_REQUEST_EXPIRED: 'FRIEND_REQUEST_EXPIRED',
  FRIEND_REQUEST_FORBIDDEN: 'FRIEND_REQUEST_FORBIDDEN',
  CANNOT_FOLLOW_SELF: 'CANNOT_FOLLOW_SELF',
  ALREADY_FOLLOWING: 'ALREADY_FOLLOWING',
  NOT_FOLLOWING: 'NOT_FOLLOWING',
  CANNOT_INVITE_SELF: 'CANNOT_INVITE_SELF',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_NOT_PENDING: 'INVITATION_NOT_PENDING',
  PRESENCE_QUERY_TOO_LARGE: 'PRESENCE_QUERY_TOO_LARGE',

  // ---- Family and Rankings domain ----
  FAMILY_NOT_FOUND: 'FAMILY_NOT_FOUND',
  ALREADY_IN_FAMILY: 'ALREADY_IN_FAMILY',
  NOT_IN_FAMILY: 'NOT_IN_FAMILY',
  FAMILY_NAME_EXISTS: 'FAMILY_NAME_EXISTS',
  JOIN_REQUEST_NOT_FOUND: 'JOIN_REQUEST_NOT_FOUND',
  JOIN_REQUEST_EXISTS: 'JOIN_REQUEST_EXISTS',
  FAMILY_ROLE_FORBIDDEN: 'FAMILY_ROLE_FORBIDDEN',
  LEADER_CANNOT_LEAVE: 'LEADER_CANNOT_LEAVE',
  FAMILY_LIMIT_REACHED: 'FAMILY_LIMIT_REACHED',
  JOIN_COOLDOWN_ACTIVE: 'JOIN_COOLDOWN_ACTIVE',
};

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
