/**
 * Stable, machine-readable error codes returned in the error envelope so
 * clients can branch on failures without parsing messages. Extend per domain.
 */
export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL: 'INTERNAL',

  // ---- Auth domain ----
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  OTP_BLOCKED: 'OTP_BLOCKED',
  OTP_RESEND_LIMIT: 'OTP_RESEND_LIMIT',
  OTP_COOLDOWN: 'OTP_COOLDOWN',
  DUPLICATE_MOBILE: 'DUPLICATE_MOBILE',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  DUPLICATE_USERNAME: 'DUPLICATE_USERNAME',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  UNDERAGE: 'UNDERAGE',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_HIJACK_DETECTED: 'SESSION_HIJACK_DETECTED',
  SESSION_LIMIT: 'SESSION_LIMIT',
  GUEST_FORBIDDEN: 'GUEST_FORBIDDEN',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  INVALID_SOCIAL_TOKEN: 'INVALID_SOCIAL_TOKEN',

  // ---- User / profile domain ----
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  USERNAME_INVALID: 'USERNAME_INVALID',
  VERIFICATION_PENDING: 'VERIFICATION_PENDING',
  VERIFICATION_NOT_FOUND: 'VERIFICATION_NOT_FOUND',

  // ---- Device domain ----
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DEVICE_FORBIDDEN: 'DEVICE_FORBIDDEN',

  // ---- Privacy / Safety domain ----
  CANNOT_BLOCK_SELF: 'CANNOT_BLOCK_SELF',
  ALREADY_BLOCKED: 'ALREADY_BLOCKED',
  USER_BLOCKED: 'USER_BLOCKED',
  PRIVACY_RESTRICTED: 'PRIVACY_RESTRICTED',

  // ---- Audio Room domain ----
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_LIMIT_REACHED: 'ROOM_LIMIT_REACHED',
  ROOM_LOCKED: 'ROOM_LOCKED',
  ROOM_PASSWORD_INVALID: 'ROOM_PASSWORD_INVALID',
  ROOM_FULL: 'ROOM_FULL',
  ROOM_ENDED: 'ROOM_ENDED',
  NOT_ROOM_OWNER: 'NOT_ROOM_OWNER',
  NOT_ROOM_MEMBER: 'NOT_ROOM_MEMBER',
  ROOM_CATEGORY_INVALID: 'ROOM_CATEGORY_INVALID',
  ROOM_LANGUAGE_INVALID: 'ROOM_LANGUAGE_INVALID',

  // ---- Audio Room seats / roles (AR-1) ----
  NOT_ROOM_ADMIN: 'NOT_ROOM_ADMIN',
  SEAT_NOT_FOUND: 'SEAT_NOT_FOUND',
  SEAT_TAKEN: 'SEAT_TAKEN',
  SEAT_LOCKED: 'SEAT_LOCKED',
  SEAT_FULL: 'SEAT_FULL',
  ALREADY_ON_SEAT: 'ALREADY_ON_SEAT',
  NOT_ON_SEAT: 'NOT_ON_SEAT',
  SEAT_TYPE_FORBIDDEN: 'SEAT_TYPE_FORBIDDEN',
  SEAT_LAYOUT_INVALID: 'SEAT_LAYOUT_INVALID',
  SEAT_REQUEST_NOT_FOUND: 'SEAT_REQUEST_NOT_FOUND',
  SEAT_REQUEST_EXISTS: 'SEAT_REQUEST_EXISTS',
  SEAT_INVITATION_NOT_FOUND: 'SEAT_INVITATION_NOT_FOUND',
  SEAT_INVITATION_EXPIRED: 'SEAT_INVITATION_EXPIRED',
  QUEUE_ENTRY_NOT_FOUND: 'QUEUE_ENTRY_NOT_FOUND',
  ROLE_INVALID: 'ROLE_INVALID',

  // ---- Audio Room voice (AR-2) ----
  VOICE_NOT_CONFIGURED: 'VOICE_NOT_CONFIGURED',
  VOICE_SESSION_NOT_FOUND: 'VOICE_SESSION_NOT_FOUND',
  VOICE_NOT_IN_CHANNEL: 'VOICE_NOT_IN_CHANNEL',
  NOT_ALLOWED_TO_PUBLISH: 'NOT_ALLOWED_TO_PUBLISH',

  // ---- Audio Room moderation (AR-3) ----
  ROOM_BANNED: 'ROOM_BANNED',
  ALREADY_BANNED: 'ALREADY_BANNED',
  BAN_NOT_FOUND: 'BAN_NOT_FOUND',
  MEMBER_MUTED: 'MEMBER_MUTED',
  ALREADY_MUTED: 'ALREADY_MUTED',
  MUTE_NOT_FOUND: 'MUTE_NOT_FOUND',
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  DUPLICATE_REPORT: 'DUPLICATE_REPORT',
  CANNOT_MODERATE_OWNER: 'CANNOT_MODERATE_OWNER',
  CANNOT_MODERATE_SELF: 'CANNOT_MODERATE_SELF',
  INSUFFICIENT_AUTHORITY: 'INSUFFICIENT_AUTHORITY',
  APPEAL_EXISTS: 'APPEAL_EXISTS',
  APPEAL_NOT_FOUND: 'APPEAL_NOT_FOUND',

  // ---- Audio Room chat (AR-4) ----
  CHAT_DISABLED: 'CHAT_DISABLED',
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',
  CHAT_RATE_LIMITED: 'CHAT_RATE_LIMITED',
  CHAT_SLOW_MODE: 'CHAT_SLOW_MODE',
  DUPLICATE_MESSAGE: 'DUPLICATE_MESSAGE',
  BLOCKED_WORD: 'BLOCKED_WORD',
  ALREADY_PINNED: 'ALREADY_PINNED',
  PIN_NOT_FOUND: 'PIN_NOT_FOUND',
  CHAT_REPORT_NOT_FOUND: 'CHAT_REPORT_NOT_FOUND',
  BLOCKED_WORD_NOT_FOUND: 'BLOCKED_WORD_NOT_FOUND',
  INVALID_REGEX: 'INVALID_REGEX',

  // ---- Wallet (economy) ----
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  UNSUPPORTED_CURRENCY: 'UNSUPPORTED_CURRENCY',
  WALLET_TXN_NOT_FOUND: 'WALLET_TXN_NOT_FOUND',

  // ---- Gifts (AR-5) ----
  GIFT_NOT_FOUND: 'GIFT_NOT_FOUND',
  GIFT_DISABLED: 'GIFT_DISABLED',
  GIFT_INVALID_QUANTITY: 'GIFT_INVALID_QUANTITY',
  GIFT_VIP_RESTRICTED: 'GIFT_VIP_RESTRICTED',
  CANNOT_GIFT_SELF: 'CANNOT_GIFT_SELF',
  GIFT_RECEIVER_INVALID: 'GIFT_RECEIVER_INVALID',
  GIFT_CONTEXT_INVALID: 'GIFT_CONTEXT_INVALID',
  GIFT_RATE_LIMITED: 'GIFT_RATE_LIMITED',
  DUPLICATE_GIFT: 'DUPLICATE_GIFT',

  // ---- Backpack ----
  BACKPACK_ITEM_NOT_FOUND: 'BACKPACK_ITEM_NOT_FOUND',
  BACKPACK_ITEM_NOT_EQUIPPABLE: 'BACKPACK_ITEM_NOT_EQUIPPABLE',
  BACKPACK_ITEM_NOT_TRANSFERABLE: 'BACKPACK_ITEM_NOT_TRANSFERABLE',
  BACKPACK_ITEM_EXPIRED: 'BACKPACK_ITEM_EXPIRED',
  CANNOT_TRANSFER_SELF: 'CANNOT_TRANSFER_SELF',

  // ---- Treasure boxes & rocket events (AR-6) ----
  TREASURE_CONFIG_INCOMPLETE: 'TREASURE_CONFIG_INCOMPLETE',
  TREASURE_SESSION_EXISTS: 'TREASURE_SESSION_EXISTS',
  TREASURE_SESSION_NOT_FOUND: 'TREASURE_SESSION_NOT_FOUND',
  TREASURE_NOT_AUTHORIZED: 'TREASURE_NOT_AUTHORIZED',
  TREASURE_CONFIG_NOT_FOUND: 'TREASURE_CONFIG_NOT_FOUND',
  ROCKET_CONFIG_NOT_FOUND: 'ROCKET_CONFIG_NOT_FOUND',

  // ---- Cosmetics / EXP / Levels / VIP (AR-7) ----
  COSMETIC_NOT_FOUND: 'COSMETIC_NOT_FOUND',
  LEVEL_CONFIG_NOT_FOUND: 'LEVEL_CONFIG_NOT_FOUND',
  VIP_CONFIG_NOT_FOUND: 'VIP_CONFIG_NOT_FOUND',

  // ---- Events / Room appearance (AR-8) ----
  EVENT_NOT_FOUND: 'EVENT_NOT_FOUND',
  EVENT_NOT_ACTIVE: 'EVENT_NOT_ACTIVE',
  EVENT_ALREADY_CLAIMED: 'EVENT_ALREADY_CLAIMED',
  EVENT_NOT_ELIGIBLE: 'EVENT_NOT_ELIGIBLE',
  EVENT_NOT_CLAIMABLE: 'EVENT_NOT_CLAIMABLE',
  EVENT_INVALID_WINDOW: 'EVENT_INVALID_WINDOW',
  COSMETIC_NOT_OWNED: 'COSMETIC_NOT_OWNED',
  COSMETIC_WRONG_TYPE: 'COSMETIC_WRONG_TYPE',
  APPEARANCE_NOT_AUTHORIZED: 'APPEARANCE_NOT_AUTHORIZED',

  // ---- Premium features (AR-9) ----
  COSMETIC_NOT_PURCHASABLE: 'COSMETIC_NOT_PURCHASABLE',
  PREMIUM_SEAT_UNAVAILABLE: 'PREMIUM_SEAT_UNAVAILABLE',
  PREMIUM_SEAT_ALREADY_HELD: 'PREMIUM_SEAT_ALREADY_HELD',
  ALREADY_ELEVATED: 'ALREADY_ELEVATED',
  PREMIUM_SEAT_NOT_FOUND: 'PREMIUM_SEAT_NOT_FOUND',
  WATCH_PARTY_NOT_AUTHORIZED: 'WATCH_PARTY_NOT_AUTHORIZED',
  WATCH_PARTY_INACTIVE: 'WATCH_PARTY_INACTIVE',
  INVALID_VIDEO_ID: 'INVALID_VIDEO_ID',

  // ---- PK Battles (AR-10) ----
  PK_NOT_AUTHORIZED: 'PK_NOT_AUTHORIZED',
  PK_ALREADY_ACTIVE: 'PK_ALREADY_ACTIVE',
  PK_NOT_FOUND: 'PK_NOT_FOUND',
  PK_INVALID_PARTICIPANTS: 'PK_INVALID_PARTICIPANTS',
  PK_PARTICIPANT_NOT_MEMBER: 'PK_PARTICIPANT_NOT_MEMBER',

  // ---- Analytics & Reporting (AR-13) ----
  ANALYTICS_NOT_AUTHORIZED: 'ANALYTICS_NOT_AUTHORIZED',

  // ---- Games (AR-11) ----
  GAME_NOT_FOUND: 'GAME_NOT_FOUND',
  GAME_DISABLED: 'GAME_DISABLED',
  GAME_INVALID_STAKE: 'GAME_INVALID_STAKE',
  GAME_LOBBY_NOT_FOUND: 'GAME_LOBBY_NOT_FOUND',
  GAME_LOBBY_NOT_OPEN: 'GAME_LOBBY_NOT_OPEN',
  GAME_LOBBY_FULL: 'GAME_LOBBY_FULL',
  GAME_ALREADY_IN_LOBBY: 'GAME_ALREADY_IN_LOBBY',
  GAME_NOT_IN_LOBBY: 'GAME_NOT_IN_LOBBY',
  GAME_NOT_HOST: 'GAME_NOT_HOST',
  GAME_INSUFFICIENT_PLAYERS: 'GAME_INSUFFICIENT_PLAYERS',
  GAME_SESSION_NOT_FOUND: 'GAME_SESSION_NOT_FOUND',
  GAME_SESSION_NOT_ACTIVE: 'GAME_SESSION_NOT_ACTIVE',
  GAME_ALREADY_SETTLED: 'GAME_ALREADY_SETTLED',
  GAME_INVALID_PAYOUT: 'GAME_INVALID_PAYOUT',
  GAME_PAYOUT_EXCEEDS_POT: 'GAME_PAYOUT_EXCEEDS_POT',
  GAME_INVALID_PARTICIPANT: 'GAME_INVALID_PARTICIPANT',
  GAME_NOT_AUTHORIZED: 'GAME_NOT_AUTHORIZED',

  // ---- Lucky Packets (AR-14) ----
  LUCKY_PACKET_NOT_AUTHORIZED: 'LUCKY_PACKET_NOT_AUTHORIZED',
  LUCKY_PACKET_INVALID_PARAMS: 'LUCKY_PACKET_INVALID_PARAMS',
  LUCKY_PACKET_NOT_FOUND: 'LUCKY_PACKET_NOT_FOUND',
  LUCKY_PACKET_EXPIRED: 'LUCKY_PACKET_EXPIRED',
  LUCKY_PACKET_EXHAUSTED: 'LUCKY_PACKET_EXHAUSTED',
  LUCKY_PACKET_ALREADY_CLAIMED: 'LUCKY_PACKET_ALREADY_CLAIMED',

  // ---- Room Interactive Utilities (AR-15) ----
  ROOM_UTIL_NOT_AUTHORIZED: 'ROOM_UTIL_NOT_AUTHORIZED',
  POLL_NOT_FOUND: 'POLL_NOT_FOUND',
  POLL_ENDED: 'POLL_ENDED',
  POLL_ALREADY_VOTED: 'POLL_ALREADY_VOTED',
  POLL_OPTION_INVALID: 'POLL_OPTION_INVALID',
  RANDOM_PICK_INVALID_RANGE: 'RANDOM_PICK_INVALID_RANGE',
  RANDOM_PICK_NO_CANDIDATES: 'RANDOM_PICK_NO_CANDIDATES',
  SPIN_WHEEL_NOT_FOUND: 'SPIN_WHEEL_NOT_FOUND',
  COUNTDOWN_EXISTS: 'COUNTDOWN_EXISTS',
  COUNTDOWN_NOT_FOUND: 'COUNTDOWN_NOT_FOUND',
  COUNTDOWN_NOT_RUNNING: 'COUNTDOWN_NOT_RUNNING',
  COUNTDOWN_NOT_PAUSED: 'COUNTDOWN_NOT_PAUSED',

  // ---- Social graph (friends / follow / invitations) ----
  CANNOT_FRIEND_SELF: 'CANNOT_FRIEND_SELF',
  ALREADY_FRIENDS: 'ALREADY_FRIENDS',
  NOT_FRIENDS: 'NOT_FRIENDS',
  FRIEND_REQUEST_NOT_FOUND: 'FRIEND_REQUEST_NOT_FOUND',
  FRIEND_REQUEST_EXISTS: 'FRIEND_REQUEST_EXISTS',
  FRIEND_REQUEST_EXPIRED: 'FRIEND_REQUEST_EXPIRED',
  FRIEND_REQUEST_FORBIDDEN: 'FRIEND_REQUEST_FORBIDDEN',
  CANNOT_FOLLOW_SELF: 'CANNOT_FOLLOW_SELF',
  ALREADY_FOLLOWING: 'ALREADY_FOLLOWING',
  NOT_FOLLOWING: 'NOT_FOLLOWING',
  CANNOT_INVITE_SELF: 'CANNOT_INVITE_SELF',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_NOT_PENDING: 'INVITATION_NOT_PENDING',
  PRESENCE_QUERY_TOO_LARGE: 'PRESENCE_QUERY_TOO_LARGE',

  // ---- Family and Rankings domain ----
  FAMILY_NOT_FOUND: 'FAMILY_NOT_FOUND',
  ALREADY_IN_FAMILY: 'ALREADY_IN_FAMILY',
  NOT_IN_FAMILY: 'NOT_IN_FAMILY',
  FAMILY_NAME_EXISTS: 'FAMILY_NAME_EXISTS',
  JOIN_REQUEST_NOT_FOUND: 'JOIN_REQUEST_NOT_FOUND',
  JOIN_REQUEST_EXISTS: 'JOIN_REQUEST_EXISTS',
  FAMILY_ROLE_FORBIDDEN: 'FAMILY_ROLE_FORBIDDEN',
  LEADER_CANNOT_LEAVE: 'LEADER_CANNOT_LEAVE',
  FAMILY_LIMIT_REACHED: 'FAMILY_LIMIT_REACHED',
};

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
