import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const SYSTEM_ROLES = [
  'SUPER_ADMIN',
  'ADMIN',
  'COUNTRY_MANAGER',
  'OFFICIAL',
  'MODERATOR',
  'BUSINESS_DEVELOPMENT',
  'AGENCY',
  'COIN_SELLER',
  'HOST',
  'USER',
];

const DEFAULT_PERMISSIONS = [
  {
    code: 'user.view',
    module: 'user',
    action: 'view',
    category: 'USER',
    displayName: 'View Users',
    description: 'Can view user profile details and list users',
  },
  {
    code: 'user.update',
    module: 'user',
    action: 'update',
    category: 'USER',
    displayName: 'Update User',
    description: 'Can update user profiles and account details',
  },
  {
    code: 'user.ban',
    module: 'user',
    action: 'ban',
    category: 'USER',
    displayName: 'Ban User',
    description: 'Can suspend or ban user accounts',
  },
  {
    code: 'user.delete',
    module: 'user',
    action: 'delete',
    category: 'USER',
    displayName: 'Delete User',
    description: 'Can soft or hard delete user accounts',
  },
  {
    code: 'wallet.view',
    module: 'wallet',
    action: 'view',
    category: 'WALLET',
    displayName: 'View Wallet',
    description: 'Can view wallet balances and transactions',
  },
  {
    code: 'wallet.adjust',
    module: 'wallet',
    action: 'adjust',
    category: 'WALLET',
    displayName: 'Adjust Wallet',
    description: 'Can credit/debit user balances manually',
  },
  {
    code: 'room.create',
    module: 'room',
    action: 'create',
    category: 'ROOM',
    displayName: 'Create Room',
    description: 'Can create audio/video rooms',
  },
  {
    code: 'room.update',
    module: 'room',
    action: 'update',
    category: 'ROOM',
    displayName: 'Update Room',
    description: 'Can update room settings and metadata',
  },
  {
    code: 'room.close',
    module: 'room',
    action: 'close',
    category: 'ROOM',
    displayName: 'Close Room',
    description: 'Can forcefully close audio/video rooms',
  },
  {
    code: 'room.delete',
    module: 'room',
    action: 'delete',
    category: 'ROOM',
    displayName: 'Delete Room',
    description: 'Can delete room records',
  },
  {
    code: 'room.mute',
    module: 'room',
    action: 'mute',
    category: 'ROOM',
    displayName: 'Mute Room User',
    description: 'Can mute users in audio/video rooms',
  },
  {
    code: 'agency.create',
    module: 'agency',
    action: 'create',
    category: 'AGENCY',
    displayName: 'Create Agency',
    description: 'Can create new host/talent agencies',
  },
  {
    code: 'agency.approve',
    module: 'agency',
    action: 'approve',
    category: 'AGENCY',
    displayName: 'Approve Agency',
    description: 'Can approve agency registration requests',
  },
  {
    code: 'agency.reject',
    module: 'agency',
    action: 'reject',
    category: 'AGENCY',
    displayName: 'Reject Agency',
    description: 'Can reject agency registration requests',
  },
  {
    code: 'seller.approve',
    module: 'seller',
    action: 'approve',
    category: 'COIN_SELLER',
    displayName: 'Approve Coin Seller',
    description: 'Can approve coin seller applications',
  },
  {
    code: 'seller.reject',
    module: 'seller',
    action: 'reject',
    category: 'COIN_SELLER',
    displayName: 'Reject Coin Seller',
    description: 'Can reject coin seller applications',
  },
  {
    code: 'event.create',
    module: 'event',
    action: 'create',
    category: 'EVENT',
    displayName: 'Create Event',
    description: 'Can create platform events',
  },
  {
    code: 'event.publish',
    module: 'event',
    action: 'publish',
    category: 'EVENT',
    displayName: 'Publish Event',
    description: 'Can publish scheduled events',
  },
  {
    code: 'analytics.view',
    module: 'analytics',
    action: 'view',
    category: 'ANALYTICS',
    displayName: 'View Analytics',
    description: 'Can view platform analytics and operational metrics',
  },
  {
    code: 'gift.manage',
    module: 'gift',
    action: 'manage',
    category: 'GIFTS',
    displayName: 'Manage Gifts',
    description: 'Can configure virtual gifts and pricing',
  },
  {
    code: 'coin.manage',
    module: 'coin',
    action: 'manage',
    category: 'COIN',
    displayName: 'Manage Coins',
    description: 'Can manage coin rates, packages, and distributions',
  },
  {
    code: 'game.manage',
    module: 'game',
    action: 'manage',
    category: 'GAME',
    displayName: 'Manage Games',
    description: 'Can configure platform mini-games and rules',
  },
  {
    code: 'vip.manage',
    module: 'vip',
    action: 'manage',
    category: 'VIP',
    displayName: 'Manage VIP',
    description: 'Can manage VIP tiers, perks, and subscriptions',
  },
  {
    code: 'treasure.view',
    module: 'treasure',
    action: 'view',
    category: 'TREASURE',
    displayName: 'View Treasure Box',
    description: 'Can view live treasure box status and progress',
  },
  {
    code: 'treasure.history.view',
    module: 'treasure',
    action: 'history.view',
    category: 'TREASURE',
    displayName: 'View Treasure History',
    description: 'Can view treasure session and reward history',
  },
  {
    code: 'treasure.audit.view',
    module: 'treasure',
    action: 'audit.view',
    category: 'TREASURE',
    displayName: 'View Treasure Audit',
    description: 'Can view treasure audit events',
  },
  {
    code: 'treasure.configuration.manage',
    module: 'treasure',
    action: 'configuration.manage',
    category: 'TREASURE',
    displayName: 'Manage Treasure Configuration',
    description: 'Can configure treasure box thresholds and reward pools',
  },
  {
    code: 'revenue.view',
    module: 'revenue',
    action: 'view',
    category: 'REVENUE',
    displayName: 'View Revenue',
    description: 'Can view host revenue summaries and statistics',
  },
  {
    code: 'revenue.history.view',
    module: 'revenue',
    action: 'history.view',
    category: 'REVENUE',
    displayName: 'View Revenue History',
    description: 'Can view revenue distribution history logs',
  },
  {
    code: 'revenue.audit.view',
    module: 'revenue',
    action: 'audit.view',
    category: 'REVENUE',
    displayName: 'View Revenue Audit',
    description: 'Can view revenue audit logs',
  },
  {
    code: 'revenue.configuration.manage',
    module: 'revenue',
    action: 'configuration.manage',
    category: 'REVENUE',
    displayName: 'Manage Revenue Configuration',
    description: 'Can configure revenue split percentages',
  },
  {
    code: 'agency.settlement.view',
    module: 'agency',
    action: 'settlement.view',
    category: 'AGENCY',
    displayName: 'View Agency Settlement',
    description: 'Can view agency settlement summaries and statistics',
  },
  {
    code: 'agency.settlement.history.view',
    module: 'agency',
    action: 'settlement.history.view',
    category: 'AGENCY',
    displayName: 'View Agency Settlement History',
    description: 'Can view agency settlement history logs',
  },
  {
    code: 'agency.settlement.audit.view',
    module: 'agency',
    action: 'settlement.audit.view',
    category: 'AGENCY',
    displayName: 'View Agency Settlement Audit',
    description: 'Can view agency settlement audit logs',
  },
  {
    code: 'agency.settlement.configuration.manage',
    module: 'agency',
    action: 'settlement.configuration.manage',
    category: 'AGENCY',
    displayName: 'Manage Agency Settlement Configuration',
    description: 'Can configure agency commission percentages',
  },
  {
    code: 'coin_seller.settlement.view',
    module: 'coin_seller',
    action: 'settlement.view',
    category: 'COIN_SELLER',
    displayName: 'View Coin Seller Settlement',
    description: 'Can view coin seller settlement summaries and statistics',
  },
  {
    code: 'coin_seller.settlement.history.view',
    module: 'coin_seller',
    action: 'settlement.history.view',
    category: 'COIN_SELLER',
    displayName: 'View Coin Seller Settlement History',
    description: 'Can view coin seller settlement history logs',
  },
  {
    code: 'coin_seller.settlement.audit.view',
    module: 'coin_seller',
    action: 'settlement.audit.view',
    category: 'COIN_SELLER',
    displayName: 'View Coin Seller Settlement Audit',
    description: 'Can view coin seller settlement audit logs',
  },
  {
    code: 'coin_seller.settlement.configuration.manage',
    module: 'coin_seller',
    action: 'settlement.configuration.manage',
    category: 'COIN_SELLER',
    displayName: 'Manage Coin Seller Settlement Configuration',
    description: 'Can configure coin seller commission percentages',
  },
  {
    code: 'withdrawal.request',
    module: 'withdrawal',
    action: 'request',
    category: 'WITHDRAWAL',
    displayName: 'Request Withdrawal',
    description: 'Can request withdrawal of eligible earnings',
  },
  {
    code: 'withdrawal.view',
    module: 'withdrawal',
    action: 'view',
    category: 'WITHDRAWAL',
    displayName: 'View Withdrawal',
    description: 'Can view withdrawal summaries and statistics',
  },
  {
    code: 'withdrawal.history.view',
    module: 'withdrawal',
    action: 'history.view',
    category: 'WITHDRAWAL',
    displayName: 'View Withdrawal History',
    description: 'Can view withdrawal history logs',
  },
  {
    code: 'withdrawal.audit.view',
    module: 'withdrawal',
    action: 'audit.view',
    category: 'WITHDRAWAL',
    displayName: 'View Withdrawal Audit',
    description: 'Can view withdrawal audit logs',
  },
  {
    code: 'withdrawal.approve',
    module: 'withdrawal',
    action: 'approve',
    category: 'WITHDRAWAL',
    displayName: 'Approve Withdrawal',
    description: 'Can review, approve, or reject withdrawal requests',
  },
  {
    code: 'withdrawal.configuration.manage',
    module: 'withdrawal',
    action: 'configuration.manage',
    category: 'WITHDRAWAL',
    displayName: 'Manage Withdrawal Configuration',
    description: 'Can configure withdrawal thresholds, limits, and fees',
  },
  {
    code: 'family.create',
    module: 'family',
    action: 'create',
    category: 'FAMILY',
    displayName: 'Create Family',
    description: 'Can create a new family community',
  },
  {
    code: 'family.view',
    module: 'family',
    action: 'view',
    category: 'FAMILY',
    displayName: 'View Family',
    description: 'Can view family details and statistics',
  },
  {
    code: 'family.update',
    module: 'family',
    action: 'update',
    category: 'FAMILY',
    displayName: 'Update Family',
    description: 'Can update family profile and announcements',
  },
  {
    code: 'family.delete',
    module: 'family',
    action: 'delete',
    category: 'FAMILY',
    displayName: 'Delete Family',
    description: 'Can delete or disband a family',
  },
  {
    code: 'family.member.manage',
    module: 'family',
    action: 'member.manage',
    category: 'FAMILY',
    displayName: 'Manage Family Members',
    description: 'Can invite, approve, kick, or ban family members',
  },
  {
    code: 'family.role.manage',
    module: 'family',
    action: 'role.manage',
    category: 'FAMILY',
    displayName: 'Manage Family Roles',
    description: 'Can promote, demote, or configure family roles',
  },
  {
    code: 'family.audit.view',
    module: 'family',
    action: 'audit.view',
    category: 'FAMILY',
    displayName: 'View Family Audit',
    description: 'Can view family audit event logs',
  },
  {
    code: 'family.statistics.view',
    module: 'family',
    action: 'statistics.view',
    category: 'FAMILY',
    displayName: 'View Family Statistics',
    description: 'Can view family growth and member statistics',
  },
  {
    code: 'vip.view',
    module: 'vip',
    action: 'view',
    category: 'VIP',
    displayName: 'View VIP',
    description: 'Can view VIP membership and active benefits',
  },
  {
    code: 'vip.purchase',
    module: 'vip',
    action: 'purchase',
    category: 'VIP',
    displayName: 'Purchase VIP',
    description: 'Can purchase or renew VIP membership subscriptions',
  },
  {
    code: 'vip.manage',
    module: 'vip',
    action: 'manage',
    category: 'VIP',
    displayName: 'Manage VIP',
    description: 'Can suspend, revoke, restore, or grant VIP memberships',
  },
  {
    code: 'vip.configuration.manage',
    module: 'vip',
    action: 'configuration.manage',
    category: 'VIP',
    displayName: 'Manage VIP Configuration',
    description: 'Can configure VIP tiers, benefits, and price settings',
  },
  {
    code: 'vip.audit.view',
    module: 'vip',
    action: 'audit.view',
    category: 'VIP',
    displayName: 'View VIP Audit',
    description: 'Can view VIP operational audit event logs',
  },
  {
    code: 'vip.statistics.view',
    module: 'vip',
    action: 'statistics.view',
    category: 'VIP',
    displayName: 'View VIP Statistics',
    description: 'Can view VIP sales and renewal statistics',
  },
  // Phase 13: Level & Experience Engine Permissions
  {
    code: 'level.view',
    module: 'exp',
    action: 'view',
    category: 'LEVEL',
    displayName: 'View User Level & EXP',
    description: 'Can view user level, progress, and experience history',
  },
  {
    code: 'level.manage',
    module: 'exp',
    action: 'manage',
    category: 'LEVEL',
    displayName: 'Manage User Levels & EXP',
    description: 'Can award or deduct user EXP and trigger level recalculation',
  },
  {
    code: 'level.configuration.manage',
    module: 'exp',
    action: 'configuration.manage',
    category: 'LEVEL',
    displayName: 'Manage Level Configuration',
    description: 'Can configure level definitions, thresholds, and EXP sources',
  },
  {
    code: 'level.audit.view',
    module: 'exp',
    action: 'audit.view',
    category: 'LEVEL',
    displayName: 'View Level Audit Logs',
    description: 'Can view operational audit logs for level engine events',
  },
  {
    code: 'level.statistics.view',
    module: 'exp',
    action: 'statistics.view',
    category: 'LEVEL',
    displayName: 'View Level Statistics',
    description: 'Can view aggregated user progression and level statistics',
  },
  // Phase 14: Badge & Achievement Engine Permissions
  {
    code: 'achievement.view',
    module: 'achievements',
    action: 'view',
    category: 'ACHIEVEMENT',
    displayName: 'View Achievements',
    description: 'Can view achievement definitions, user achievements, and progress',
  },
  {
    code: 'achievement.manage',
    module: 'achievements',
    action: 'manage',
    category: 'ACHIEVEMENT',
    displayName: 'Manage Achievements',
    description: 'Can create, update, and manually grant achievements',
  },
  {
    code: 'badge.manage',
    module: 'achievements',
    action: 'badge.manage',
    category: 'ACHIEVEMENT',
    displayName: 'Manage Badges',
    description: 'Can create badge definitions and admin-grant badges to users',
  },
  {
    code: 'achievement.configuration.manage',
    module: 'achievements',
    action: 'configuration.manage',
    category: 'ACHIEVEMENT',
    displayName: 'Manage Achievement Configuration',
    description: 'Can update dynamic achievement engine configuration parameters',
  },
  {
    code: 'achievement.audit.view',
    module: 'achievements',
    action: 'audit.view',
    category: 'ACHIEVEMENT',
    displayName: 'View Achievement Audit Logs',
    description: 'Can view operational audit logs for the achievement engine',
  },
  {
    code: 'achievement.statistics.view',
    module: 'achievements',
    action: 'statistics.view',
    category: 'ACHIEVEMENT',
    displayName: 'View Achievement Statistics',
    description: 'Can view aggregated platform achievement and badge statistics',
  },
  // Phase 15: Ranking Engine Permissions
  {
    code: 'ranking.view',
    module: 'enterprise-rankings',
    action: 'view',
    category: 'RANKING',
    displayName: 'View Rankings',
    description: 'Can view ranking definitions, leaderboards, and positions',
  },
  {
    code: 'ranking.manage',
    module: 'enterprise-rankings',
    action: 'manage',
    category: 'RANKING',
    displayName: 'Manage Rankings',
    description: 'Can create and update ranking definitions, adjust scores, and trigger snapshots',
  },
  {
    code: 'ranking.configuration.manage',
    module: 'enterprise-rankings',
    action: 'configuration.manage',
    category: 'RANKING',
    displayName: 'Manage Ranking Configuration',
    description: 'Can update dynamic ranking engine configuration parameters',
  },
  {
    code: 'ranking.audit.view',
    module: 'enterprise-rankings',
    action: 'audit.view',
    category: 'RANKING',
    displayName: 'View Ranking Audit Logs',
    description: 'Can view operational audit logs for the ranking engine',
  },
  {
    code: 'ranking.statistics.view',
    module: 'enterprise-rankings',
    action: 'statistics.view',
    category: 'RANKING',
    displayName: 'View Ranking Statistics',
    description: 'Can view aggregated platform ranking statistics',
  },
  // Phase 16: Enterprise Events Engine Permissions
  {
    code: 'event.view',
    module: 'enterprise-events',
    action: 'view',
    category: 'EVENT',
    displayName: 'View Events',
    description: 'Can view event definitions, schedules, registrations, and participants',
  },
  {
    code: 'event.manage',
    module: 'enterprise-events',
    action: 'manage',
    category: 'EVENT',
    displayName: 'Manage Events',
    description:
      'Can create and update event definitions, manage registrations, participants, and rewards',
  },
  {
    code: 'event.configuration.manage',
    module: 'enterprise-events',
    action: 'configuration.manage',
    category: 'EVENT',
    displayName: 'Manage Event Configuration',
    description: 'Can update dynamic event engine configuration parameters',
  },
  {
    code: 'event.audit.view',
    module: 'enterprise-events',
    action: 'audit.view',
    category: 'EVENT',
    displayName: 'View Event Audit Logs',
    description: 'Can view operational audit logs for the event engine',
  },
  {
    code: 'event.statistics.view',
    module: 'enterprise-events',
    action: 'statistics.view',
    category: 'EVENT',
    displayName: 'View Event Statistics',
    description: 'Can view aggregated platform event statistics',
  },
  // Phase 17: Enterprise Tasks & Missions Engine Permissions
  {
    code: 'task.view',
    module: 'tasks',
    action: 'view',
    category: 'TASK',
    displayName: 'View Tasks & Missions',
    description: 'Can view task definitions, missions, progress, and history',
  },
  {
    code: 'task.manage',
    module: 'tasks',
    action: 'manage',
    category: 'TASK',
    displayName: 'Manage Tasks & Missions',
    description:
      'Can create and update task/mission definitions, trigger progress, and dispatch rewards',
  },
  {
    code: 'task.configuration.manage',
    module: 'tasks',
    action: 'configuration.manage',
    category: 'TASK',
    displayName: 'Manage Task Configuration',
    description: 'Can update dynamic task engine configuration parameters',
  },
  {
    code: 'task.audit.view',
    module: 'tasks',
    action: 'audit.view',
    category: 'TASK',
    displayName: 'View Task Audit Logs',
    description: 'Can view operational audit logs for the task engine',
  },
  {
    code: 'task.statistics.view',
    module: 'tasks',
    action: 'statistics.view',
    category: 'TASK',
    displayName: 'View Task Statistics',
    description: 'Can view aggregated platform task & mission statistics',
  },
  // Phase 18: Enterprise Referral System Permissions
  {
    code: 'referral.view',
    module: 'referrals',
    action: 'view',
    category: 'REFERRAL',
    displayName: 'View Referrals',
    description: 'Can view referral codes, relationships, campaigns, and histories',
  },
  {
    code: 'referral.manage',
    module: 'referrals',
    action: 'manage',
    category: 'REFERRAL',
    displayName: 'Manage Referrals',
    description:
      'Can create referral codes, register referees, qualify, cancel, and dispatch rewards',
  },
  {
    code: 'referral.configuration.manage',
    module: 'referrals',
    action: 'configuration.manage',
    category: 'REFERRAL',
    displayName: 'Manage Referral Configuration',
    description: 'Can update dynamic referral engine configuration parameters',
  },
  {
    code: 'referral.audit.view',
    module: 'referrals',
    action: 'audit.view',
    category: 'REFERRAL',
    displayName: 'View Referral Audit Logs',
    description: 'Can view operational audit logs for the referral engine',
  },
  {
    code: 'referral.statistics.view',
    module: 'referrals',
    action: 'statistics.view',
    category: 'REFERRAL',
    displayName: 'View Referral Statistics',
    description: 'Can view aggregated referral statistics, top referrers, and conversion rates',
  },
  // Phase 19: Enterprise Notification Center Permissions
  {
    code: 'notification.view',
    module: 'notifications',
    action: 'view',
    category: 'NOTIFICATION',
    displayName: 'View Notifications',
    description: 'Can view user notifications, inboxes, logs, history, and configuration',
  },
  {
    code: 'notification.manage',
    module: 'notifications',
    action: 'manage',
    category: 'NOTIFICATION',
    displayName: 'Manage Notifications',
    description: 'Can create and dispatch notifications, manage templates, read or delete items',
  },
  {
    code: 'notification.configuration.manage',
    module: 'notifications',
    action: 'configuration.manage',
    category: 'NOTIFICATION',
    displayName: 'Manage Notification Configuration',
    description: 'Can update dynamic notification engine parameters',
  },
  {
    code: 'notification.audit.view',
    module: 'notifications',
    action: 'audit.view',
    category: 'NOTIFICATION',
    displayName: 'View Notification Audit Logs',
    description: 'Can view operational audit logs for the notification center',
  },
  {
    code: 'notification.statistics.view',
    module: 'notifications',
    action: 'statistics.view',
    category: 'NOTIFICATION',
    displayName: 'View Notification Statistics',
    description: 'Can view aggregated statistics, read/delivery rates, and breakdowns',
  },
  {
    code: 'announcement.manage',
    module: 'notifications',
    action: 'announcement.manage',
    category: 'NOTIFICATION',
    displayName: 'Manage Announcements',
    description: 'Can broadcast platform announcements globally',
  },
  // Phase 20: Enterprise Reports & Analytics Engine Permissions
  {
    code: 'analytics.view',
    module: 'analytics',
    action: 'view',
    category: 'ANALYTICS',
    displayName: 'View Analytics',
    description: 'Can view dashboards, generated reports, KPIs, and snapshots',
  },
  {
    code: 'analytics.manage',
    module: 'analytics',
    action: 'manage',
    category: 'ANALYTICS',
    displayName: 'Manage Analytics',
    description:
      'Can trigger metric aggregation snapshots, generate reports, update dashboard configurations',
  },
  {
    code: 'analytics.export',
    module: 'analytics',
    action: 'export',
    category: 'ANALYTICS',
    displayName: 'Export Analytics Reports',
    description: 'Can export reports as CSV, Excel, PDF, or JSON format',
  },
  {
    code: 'analytics.configuration.manage',
    module: 'analytics',
    action: 'configuration.manage',
    category: 'ANALYTICS',
    displayName: 'Manage Analytics Configuration',
    description: 'Can update dynamic analytics parameters and intervals',
  },
  {
    code: 'analytics.audit.view',
    module: 'analytics',
    action: 'audit.view',
    category: 'ANALYTICS',
    displayName: 'View Analytics Audit Logs',
    description: 'Can view operational compliance audit logs for the reporting engine',
  },
  {
    code: 'analytics.statistics.view',
    module: 'analytics',
    action: 'statistics.view',
    category: 'ANALYTICS',
    displayName: 'View Analytics Statistics',
    description: 'Can view pre-aggregated growth and revenue statistics trends',
  },
  // Phase 21: Enterprise Business Admin Dashboard Permissions
  {
    code: 'dashboard.view',
    module: 'dashboard',
    action: 'view',
    category: 'DASHBOARD',
    displayName: 'View Dashboard',
    description:
      'Can view admin dashboard overview, layouts, widgets, and diagnostic health status',
  },
  {
    code: 'dashboard.manage',
    module: 'dashboard',
    action: 'manage',
    category: 'DASHBOARD',
    displayName: 'Manage Dashboard Layouts and Widgets',
    description:
      'Can create and configure widgets, personalized layouts, and resolve health alerts',
  },
  {
    code: 'dashboard.configuration.manage',
    module: 'dashboard',
    action: 'configuration.manage',
    category: 'DASHBOARD',
    displayName: 'Manage Dashboard Configurations',
    description: 'Can update dynamic dashboard intervals and parameters',
  },
  {
    code: 'dashboard.audit.view',
    module: 'dashboard',
    action: 'audit.view',
    category: 'DASHBOARD',
    displayName: 'View Dashboard Audit Logs',
    description: 'Can view administrative operational audit logs',
  },
  {
    code: 'dashboard.export',
    module: 'dashboard',
    action: 'export',
    category: 'DASHBOARD',
    displayName: 'Export Dashboard Data',
    description: 'Can compile and export dashboard screens to file downloads',
  },
  {
    code: 'dashboard.statistics.view',
    module: 'dashboard',
    action: 'statistics.view',
    category: 'DASHBOARD',
    displayName: 'View Dashboard Statistics',
    description: 'Can view pre-aggregated stats and metrics on dashboard operations',
  },
];

const DEFAULT_ROLE_HIERARCHY = [
  { parent: 'SUPER_ADMIN', child: 'ADMIN' },
  { parent: 'ADMIN', child: 'COUNTRY_MANAGER' },
  { parent: 'ADMIN', child: 'BUSINESS_DEVELOPMENT' },
  { parent: 'COUNTRY_MANAGER', child: 'OFFICIAL' },
  { parent: 'OFFICIAL', child: 'MODERATOR' },
  { parent: 'OFFICIAL', child: 'AGENCY' },
  { parent: 'OFFICIAL', child: 'COIN_SELLER' },
  { parent: 'MODERATOR', child: 'HOST' },
  { parent: 'HOST', child: 'USER' },
];

const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  SUPER_ADMIN: ['*'],
  ADMIN: [
    'user.view',
    'user.update',
    'user.ban',
    'user.delete',
    'wallet.view',
    'wallet.adjust',
    'room.create',
    'room.update',
    'room.close',
    'room.delete',
    'room.mute',
    'agency.create',
    'agency.approve',
    'agency.reject',
    'seller.approve',
    'seller.reject',
    'event.create',
    'event.publish',
    'analytics.view',
    'gift.manage',
    'coin.manage',
    'game.manage',
    'vip.manage',
    'level.view',
    'level.manage',
    'level.configuration.manage',
    'level.audit.view',
    'level.statistics.view',
    'achievement.view',
    'achievement.manage',
    'badge.manage',
    'achievement.configuration.manage',
    'achievement.audit.view',
    'achievement.statistics.view',
    'ranking.view',
    'ranking.manage',
    'ranking.configuration.manage',
    'ranking.audit.view',
    'ranking.statistics.view',
    'event.view',
    'event.manage',
    'event.configuration.manage',
    'event.audit.view',
    'event.statistics.view',
    'task.view',
    'task.manage',
    'task.configuration.manage',
    'task.audit.view',
    'task.statistics.view',
  ],
  COUNTRY_MANAGER: [
    'user.view',
    'user.update',
    'user.ban',
    'wallet.view',
    'room.create',
    'room.update',
    'room.close',
    'room.mute',
    'agency.create',
    'agency.approve',
    'agency.reject',
    'seller.approve',
    'seller.reject',
    'event.create',
    'event.publish',
    'analytics.view',
  ],
  OFFICIAL: [
    'user.view',
    'user.update',
    'user.ban',
    'room.create',
    'room.update',
    'room.close',
    'room.mute',
    'agency.approve',
    'agency.reject',
    'seller.approve',
    'seller.reject',
    'event.create',
  ],
  MODERATOR: ['user.view', 'user.ban', 'room.update', 'room.close', 'room.mute'],
  BUSINESS_DEVELOPMENT: [
    'user.view',
    'agency.create',
    'agency.approve',
    'seller.approve',
    'analytics.view',
  ],
  AGENCY: ['user.view', 'room.create'],
  COIN_SELLER: ['wallet.view'],
  HOST: ['room.create', 'room.update'],
  USER: ['room.create'],
};

async function main() {
  console.log('Starting standalone RBAC seed script...');

  const roleMap = new Map<string, string>();
  for (const roleName of SYSTEM_ROLES) {
    const role = await prisma.role.upsert({
      where: { name: roleName },
      create: {
        name: roleName,
        displayName: roleName.replace(/_/g, ' '),
        description: `System defined ${roleName} role`,
        isSystem: true,
      },
      update: { isSystem: true },
    });
    roleMap.set(roleName, role.id);
  }
  console.log(`Roles seeded: ${roleMap.size}`);

  const permMap = new Map<string, string>();
  for (const p of DEFAULT_PERMISSIONS) {
    const perm = await prisma.permission.upsert({
      where: { code: p.code },
      create: {
        code: p.code,
        module: p.module,
        action: p.action,
        category: p.category || 'SYSTEM',
        displayName: p.displayName,
        description: p.description,
      },
      update: {
        category: p.category || 'SYSTEM',
        displayName: p.displayName,
        description: p.description,
      },
    });
    permMap.set(p.code, perm.id);
  }
  console.log(`Permissions seeded: ${permMap.size}`);

  for (const [roleName, permCodes] of Object.entries(DEFAULT_ROLE_PERMISSIONS)) {
    const roleId = roleMap.get(roleName);
    if (!roleId) continue;

    if (permCodes.includes('*')) {
      for (const permId of permMap.values()) {
        await prisma.rolePermission.upsert({
          where: { roleId_permissionId: { roleId, permissionId: permId } },
          create: { roleId, permissionId: permId },
          update: {},
        });
      }
    } else {
      for (const code of permCodes) {
        const permId = permMap.get(code);
        if (!permId) continue;
        await prisma.rolePermission.upsert({
          where: { roleId_permissionId: { roleId, permissionId: permId } },
          create: { roleId, permissionId: permId },
          update: {},
        });
      }
    }
  }
  console.log('Role-Permission mappings seeded.');

  for (const edge of DEFAULT_ROLE_HIERARCHY) {
    const parentRoleId = roleMap.get(edge.parent);
    const childRoleId = roleMap.get(edge.child);
    if (parentRoleId && childRoleId) {
      await prisma.roleHierarchy.upsert({
        where: { parentRoleId_childRoleId: { parentRoleId, childRoleId } },
        create: { parentRoleId, childRoleId },
        update: {},
      });
    }
  }
  console.log('Role hierarchy seeded.');

  const country = await prisma.country.upsert({
    where: { code: 'IN' },
    create: { code: 'IN', name: 'India' },
    update: { name: 'India' },
  });

  const state = await prisma.state.upsert({
    where: { countryId_code: { countryId: country.id, code: 'KA' } },
    create: { countryId: country.id, code: 'KA', name: 'Karnataka' },
    update: { name: 'Karnataka' },
  });

  await prisma.region.upsert({
    where: { stateId_code: { stateId: state.id, code: 'BLR' } },
    create: { stateId: state.id, code: 'BLR', name: 'Bengaluru Region' },
    update: { name: 'Bengaluru Region' },
  });

  console.log('Geographic reference data seeded successfully.');
}

main()
  .catch((e) => {
    console.error('Error during RBAC seed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
