-- CreateEnum
CREATE TYPE "PlatformRole" AS ENUM ('SUPER_ADMIN', 'ADMIN', 'COUNTRY_MANAGER', 'OFFICIAL', 'MODERATOR', 'BUSINESS_DEV', 'AGENCY', 'COIN_SELLER', 'HOST', 'USER');

-- CreateEnum
CREATE TYPE "CurrencyType" AS ENUM ('GOLD', 'FREE');
