import {
  VIDEO_ROOM_ANALYTICS_ACTIVE_HOSTS_KEY,
  VIDEO_ROOM_ANALYTICS_ACTIVE_PARTICIPANTS_KEY,
  VIDEO_ROOM_ANALYTICS_ACTIVE_ROOMS_KEY,
  VIDEO_ROOM_ANALYTICS_ACTIVE_VIEWERS_KEY,
  VIDEO_ROOM_ANALYTICS_CONCURRENT_GIFTS_KEY,
  VIDEO_ROOM_ANALYTICS_CONCURRENT_PK_KEY,
  VIDEO_ROOM_ANALYTICS_CONCURRENT_TREASURE_KEY,
  VIDEO_ROOM_QUEUES,
  videoRoomAnalyticsCacheKey,
} from './video-room.constants';

export const VIDEO_ROOM_ANALYTICS_QUEUES = {
  AGGREGATION: VIDEO_ROOM_QUEUES.ANALYTICS,
} as const;

export const VIDEO_ROOM_ANALYTICS_REDIS_KEYS = {
  ACTIVE_ROOMS: VIDEO_ROOM_ANALYTICS_ACTIVE_ROOMS_KEY,
  ACTIVE_HOSTS: VIDEO_ROOM_ANALYTICS_ACTIVE_HOSTS_KEY,
  ACTIVE_PARTICIPANTS: VIDEO_ROOM_ANALYTICS_ACTIVE_PARTICIPANTS_KEY,
  ACTIVE_VIEWERS: VIDEO_ROOM_ANALYTICS_ACTIVE_VIEWERS_KEY,
  CONCURRENT_PK: VIDEO_ROOM_ANALYTICS_CONCURRENT_PK_KEY,
  CONCURRENT_GIFTS: VIDEO_ROOM_ANALYTICS_CONCURRENT_GIFTS_KEY,
  CONCURRENT_TREASURE: VIDEO_ROOM_ANALYTICS_CONCURRENT_TREASURE_KEY,
  CACHE_ROOM: videoRoomAnalyticsCacheKey,
} as const;
