import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { DayOfWeek } from '@prisma/client';
import {
  ArrayNotEmpty,
  IsArray,
  IsEmail,
  IsEnum,
  IsInt,
  IsOptional,
  IsString,
  IsUUID,
  Max,
  Min,
  MinLength,
} from 'class-validator';

/**
 * Payload for provisioning a Moderator account.
 *
 * Deliberately minimal: the admin supplies only what can't be derived —
 * credentials, the moderator's operational state(s), and their working
 * shift. Username and full name are auto-generated by the service (see
 * `ModeratorProvisioningService.createModerator`) so the account stays
 * anonymous by construction. Profile geography (`User.country` and its
 * FKs) is never touched by provisioning — operational scope assignment
 * goes to `RoleScope` only, independent of profile geography.
 */
export class CreateModeratorDto {
  @ApiProperty({ example: 'bellamkondaraviteju@gmail.com' })
  @IsEmail()
  email!: string;

  @ApiProperty({ minLength: 8, description: 'Minimum 8 characters for moderator accounts' })
  @IsString()
  @MinLength(8)
  password!: string;

  @ApiProperty({
    type: [String],
    example: ['123e4567-e89b-12d3-a456-426614174000'],
    description:
      'State IDs this moderator is authorized to operate in. Supports one or more. Country is derived per-state and used only for the display country field.',
  })
  @IsArray()
  @ArrayNotEmpty()
  @IsUUID('4', { each: true })
  stateIds!: string[];

  @ApiProperty({ example: 9, minimum: 0, maximum: 23 })
  @IsInt()
  @Min(0)
  @Max(23)
  shiftStartHour!: number;

  @ApiProperty({ example: 0, minimum: 0, maximum: 59 })
  @IsInt()
  @Min(0)
  @Max(59)
  shiftStartMinute!: number;

  @ApiProperty({ example: 15, minimum: 0, maximum: 23 })
  @IsInt()
  @Min(0)
  @Max(23)
  shiftEndHour!: number;

  @ApiProperty({ example: 0, minimum: 0, maximum: 59 })
  @IsInt()
  @Min(0)
  @Max(59)
  shiftEndMinute!: number;

  @ApiPropertyOptional({
    enum: DayOfWeek,
    isArray: true,
    description: 'Defaults to all 7 days when omitted',
  })
  @IsOptional()
  @IsArray()
  @ArrayNotEmpty()
  @IsEnum(DayOfWeek, { each: true })
  shiftDaysOfWeek?: DayOfWeek[];

  @ApiPropertyOptional({ example: 'UTC', description: 'Defaults to UTC when omitted' })
  @IsOptional()
  @IsString()
  shiftTimezone?: string;
}
